### ISSUE TITLE
facebook preview not showing correctly

### ISSUE THREAD

**Issue by Conceptcradle** [tabalinas/jssocials#10]
Hi Artem,

I integrated  jssocials plugin in the website conceptcradle.com. When I try to share in facebook the preview is only showing the title and the url. How can I display the image and description in the facebook preview? Is there a way to control the previews for facebook and google plus?

Thanks,

Con

**Comment by tabalinas** [comment]
Hi Con, 

Please, read my answer to the issue: https://github.com/tabalinas/jssocials/issues/8
