### ISSUE TITLE
Need Help with Custom Shares

### ISSUE THREAD

**Issue by bajsolinowich** [tabalinas/jssocials#100]
Hey guys, great plugin!
Can you help me with something please, I need to incorporate Slideshare and Xing.
Can you advise me how to do that, I mean, what code needs to be added to jssocials.js in order for that to work?
Thanks!

**Comment by tabalinas** [comment]
Thank you for the feedback!

for Slideshare: are you sure there is sharing with slideshare?
for XING: the share url is available here https://dev.xing.com/plugins/share_button/docs (`Share on XING with custom design` section). 
How to add a new custom share is described in the docs http://js-socials.com/docs/#custom-share

**Comment by bajsolinowich** [comment]
Thank you for fast response!
You have been very helpful!

**Comment by gorpoghosyan89** [comment]
Hi  
I have problem with custom sharing, I need  add  Xing to sharing   block,
I am writing  this code , but Xing  icon doesn't appear

        jsSocials.shares.xing = {
    label: "xing",
    logo: "fab fa-xing",
    shareUrl: "https://www.xing.com/spi/shares/new?url=[URL_TO_BE_SHARED]",
    countUrl: "#",
    getCount: function(data) {
        return data.count;
    }
-----------------------------
        jQuery("#share").jsSocials({
            showLabel: false,
            showCount: false,
            shares: ["xing"]
        });

thank you
