### ISSUE TITLE
Asking for button

### ISSUE THREAD

**Issue by mlutfi10** [tabalinas/jssocials#101]
Hi guys i wanna ask if i have my own sharing button and i wanna use JSSocial for my website how can i configure it?

**Comment by Ruud68** [comment]
If you have Joomla! there is a free plugin :) https://onlinecommunityhub.nl/joomla-extensions/jssocials

**Comment by mlutfi10** [comment]
@Ruud68 but i dont use joomla :(

**Comment by HartLarsson** [comment]
you can define every share button reading instruction here: http://js-socials.com/docs/

if you scroll down to Share paragraph you can read this example:

```
{
    share: "twitter",
    label: "Tweet",
    logo: "fa fa-twitter",
    css: "custom-class",
    shareIn: "blank",
    renderer: function() { ... }
}
```

especially the logo parameter can point to you png image for example

## logo :String
A string specifying the share logo. It accepts following values:

**css class** - any non-url string is rendered as <i class="css class"></i>. Font awesome is used by default, but it can be redefined with any other css class.
**image url** - string in image url format is rendered as <img src="image url" />.
**image base64 url** - string in image base64 url format is rendered as <img src="image base64 url" />.

**Comment by tabalinas** [comment]
@HartLarsson, thanks for the answer!
@mlutfi10, I hope it's clear now.

**Comment by mlutfi10** [comment]
hi @HartLarsson @tabalinas 
can u guys give me some example using that code? 
i use this script, i mean where i need to insert that code on my script?
`<script>
        $("#share").jsSocials({
            showLabel: false,
            showCount: false,
            shareIn: "popup",
            shares: ["facebook", "twitter", "googleplus", "linkedin"]
            
        });`

thanks

**Comment by tabalinas** [comment]
No, please read this docs section http://js-socials.com/docs/#custom-share.
So you defines your share (just as described in the docs) and then use it in configuration:

```js
 ...
 shares: ["mycustomshare", "facebook", "twitter", "googleplus", "linkedin"]
 ...
```

**Comment by HartLarsson** [comment]
i can show you how i configure my social share bar, using some custom made transparent png and avoiding fontawesome including on the head of my page:

```
<script>
$(document).ready(function() {
    $("#socialshare").jsSocials({
        showLabel: false,
        showCount: false,
        shareIn: "popup",        
        shares: [
                {
                    share: "facebook",
                    logo: "/_assets/jssocials/icons/fb-logo.png"
                }, 
                {
                    share: "twitter",
                    logo: "/_assets/jssocials/icons/tw-logo.png"
                }, 
                {
                    share: "googleplus",
                    logo: "/_assets/jssocials/icons/go-logo.png"
                 }
         ]
    });
});
</script>
```
instead specifying the png as epxlained in the docs you can define a CSS style that points to you custom icon style.

dont' forget that the CSS style you specify in the logo variable will be added here:

`<i class="<css wrote in logo var>"></i>`
