### ISSUE TITLE
Please add an option for strict data protection, making your library legal in the EU

### ISSUE THREAD

**Issue by stephanrauh** [tabalinas/jssocials#103]
I observed the FacesBook sharing button automatically sends a request to FaceBook when my HTML page is loaded. In other words, FaceBook is informed what my user is doing, without giving them the option to opt out. That, in turn, makes using the FaceBook share option illegal in Germany and, as far as I know, even in the entire EU.

Can you please modify the library such that only the FaceBook logo from the Font Awesome library is shown, but no request is sent to FaceBook until the button is clicked?

BTW, it's possible other share options are affected, too. Twitter and LinkedIn seem to be OK, but I didn't check the other options.

Thanks in advance
Stephan

**Comment by Ruud68** [comment]
Hi, there are two interactions on the facebook (and other) share button(s).
The pressing of the button that a user needs to do > it sends information to facebook
The generation of the count statistics: it calls a procedure on facebook which returns the number of times the webpage has been shared.

So the only 'unasked' for interaction to facebook is the count button. You can disable that functionality (do not show share count).

Please correct me if I am wrong :)

**Comment by stephanrauh** [comment]
OK, you're right. I was confused by an unexpected default value on our side, and the fact that my ad blocker blocks two requests when the counter is activated:
![image](https://cloud.githubusercontent.com/assets/3045767/18614674/a145ed50-7d93-11e6-9964-05a3d3e07d01.png)

**Comment by stephanrauh** [comment]
By the way, you may be interested in learning we've integrated your library in BootFaces. If there's something you want us to change, just tell us.
http://www3.bootsfaces.net/Showcase/bootstrap/SocialShare.jsf
