### ISSUE TITLE
any way to display in modal popup or iframe?

### ISSUE THREAD

**Issue by nickcom** [tabalinas/jssocials#106]
I plan to use this in a mobile site and don't want a new tab or browser popup to be created. I'd like for the share window to be contained inside an iFrame or a modal popup on the same page as the share buttons. 

Is this possible?

**Comment by tabalinas** [comment]
I guess `shareIn: "popup"` (http://js-socials.com/docs/#sharein-quot-blank-quot-quot-popup-quot-quot-self-quot) or a [Custom sharing strategy](http://js-socials.com/docs/#custom-share-strategy) should help.

**Comment by nickcom** [comment]
from what I have read the default "popup" option opens in a new window. The sample code for the custom sharing strategy also opens in a new window, albeit one that you can change the dimensions of. 

I don't want the share form to be in a new window - my question is, is it possible to open this share form inside the <I>same</I> window, either as an iframe or inside a div, with the ultimate goal to display the share form inside a modal popup.

**Comment by tabalinas** [comment]
Well, since custom share strategy allows to do anything (attach handler to the link), you are free to implement any custom logic.
