### ISSUE TITLE
After sharing event

### ISSUE THREAD

**Issue by JoomBall** [tabalinas/jssocials#107]
Is it possible to refresh the page or to add an url back to share a page? or closing window?
Is there any event more than these?

```
on: {
        click: function(e) {},
        mouseenter: function(e) {},
        mouseleave: function(e) {},
        ...
    }
```

**Comment by tabalinas** [comment]
I think you could do that with a [custom sharing strategy](http://js-socials.com/docs/#custom-share-strategy). 
Save the reference to the opened window, so you could do something similar to this http://stackoverflow.com/questions/10702344/how-to-open-and-then-close-a-window-without-getting-blocked-as-a-popup

As for the supporting events, here is what stated in docs:

> An object specifying the sharing link event handlers. Handlers for all supported by DOMElement events can be specified. The handlers will be attached to the share link.
