### ISSUE TITLE
Margin problem when using jssocial without counts and labels.

### ISSUE THREAD

**Issue by awaisdar001** [tabalinas/jssocials#109]
With the following configuration, I am having `margin-right` issue which I have added an image to indicate also. 

```
 $(selector).jsSocials({
        shares: [
        {share: "facebook", label: "Share"},
        {share: "twitter", text: title, url: short_url},
        {share: "googleplus"},
        {share: "pinterest", media: media}
       ],
        url: url,
        showCount: false,
        showLabel: false,
        shareIn: "popup"

    });
```

<img width="279" alt="screen shot 2016-10-21 at 11 38 24 am" src="https://cloud.githubusercontent.com/assets/4252738/19589016/0a867498-9783-11e6-84e3-ea2d587a12ae.png">

See the difference of the margin between facebook and twitter and twitter and Google plus.
I was able to fix it by setting the `margin: 0.3em 0.3em 0.3em 0;` here. 
https://github.com/tabalinas/jssocials/blob/0ea13a483f9a9781b7339a875f5feacf7ae18b74/dist/jssocials.css#L10

Can I submit a PR?
I am using `JSSocial==1.4.0`

**Comment by awaisdar001** [comment]
I have the fix, created a PR#110
https://github.com/tabalinas/jssocials/pull/110

**Comment by tabalinas** [comment]
I cannot reproduce the issue. 
Could you provide an example (in jsfiddle, or maybe on a page with public access)?

**Comment by mikomarrache** [comment]
Hi,

I'm encountering the same issue. Looking at the CSS of the last element:

.jssocials-share:last-child {
    margin-right: 0;
}

Is it expected?

Thanks

**Comment by tabalinas** [comment]
@mikomarrache, yes, you are right. You could open an issue for RTL support.
