### ISSUE TITLE
I want to add "hidden-lg" for mobile app share

### ISSUE THREAD

**Issue by iibasarah** [tabalinas/jssocials#113]
I want to add "hidden-lg" from bootstrap attribut for mobile app share such as whatsapp, line and viber. So those service shows in mobile browser only.

**Comment by Ruud68** [comment]
I use mobile-detect when constructing buttons (joomla plugin). True mobile / tablet / desktop detection. Not every site is on bootstrap. Some 'classic' app only platforms now are also making the move to a webplatform, so sharing is not limited only to mobile device any more.

**Comment by tabalinas** [comment]
@iibasarah, try `css` option of a share, you can pass your custom css class with it to a particular share.
