### ISSUE TITLE
dump font awesome

### ISSUE THREAD

**Issue by mspanish** [tabalinas/jssocials#116]
HI your plugin looks fantastic - but why add the enormous bloat that comes w/ Font Awesome, when you only need a small set of icons?  Why not use icomoon or something more modern? No offense to font awesome, but that is a seriously bloated set of icons!

**Comment by tabalinas** [comment]
Thank you for the feedback!
Actually, js-socials is not bound to any font, font awesome is used for demos, but any font, svg, or image can be used.

**Comment by mspanish** [comment]
yes it was super easy to switch out for icomoon. Here is a font made with icomoon, plus the CSS file to switch from Font Awesome. Thanks for the best socials plugin EVER - all the services like addtoany and sharethis were BLOATING up and slowing down my site! :)
[fonts.zip](https://github.com/tabalinas/jssocials/files/563596/fonts.zip)

**Comment by mspanish** [comment]
By the way great to see a woman here on GH - seems like we are about 1% of the population!

**Comment by tabalinas** [comment]
Thanks for the assets. I guess it makes sense to provide it on http://js-socials.com/

**Comment by mspanish** [comment]
Sure - the problem is many people just assume Font Awesome is the best choice - not realizing that it will add bloat they don't need. I've had to convert a lot of projects from Font Awesome to Icomoon and it always feels good to ditch the bloat :)

**Comment by Ruud68** [comment]
Hi @mspanish thanks for sharing your icomoon work! I am using jsSocials as a plugin on Joomla! websites that already come pre-installed with icomoon. Will for sure give your font set a go as fontawesome is indeed a heavy load compared to the small jssocials script size.
Will you be maintaining the icomoon fontset (when new sharing patforms are added)? Or can you elaborate on how to add them?
