### ISSUE TITLE
Moment when the script is executed ?

### ISSUE THREAD

**Issue by tergra** [tabalinas/jssocials#117]
Hi !

I suppose the execution of the script is postponed so that it loads the page before right ? 
I'm using jssocials.min.js and I run a Q&A website. I got an issue : 

```html
<script>
        $(".share").jsSocials({
            shares: ["facebook", "twitter", "googleplus", "pinterest"],
	    
	    url: "<?php the_permalink();?>",
	    text: "text to share",
	    showLabel: true,
	    showCount: false,
	    
        });
    </script>
```

And I put it in a file that is called several times on the page, so that it triggers for every answer to the question. I also added <?php echo the_permalink(); ?> to this file to see if it works, and it does, it echoes the content of each answer properly (http://mysite.com/q/question-title/?show_answer=1681#answer_1681, or http://mysite.com/q/question-title/?show_answer=1332#answer_1332 for instance).

The problem is that when put in the jssocials script, the url it takes is always the one from the last answer that appears on the page, http://mysite.com/q/question-title/?show_answer=718#answer_718 in this case, and not the correct ones being http://mysite.com/q/question-title/?show_answer=1681#answer_1681, or http://mysite.com/q/question-title/?show_answer=1332#answer_1332…)

The jQuery code works if I put another url (“http://test.com”) so it seems to be an issue with the moment when the script actually loads. I think it loads only on the last answer and that's when it retrieves the permalink of this answer. So is there a way to remove the delay for loading jssocials and make sure it loads at the same time as every Answer ? 

Thank you very much !!

**Comment by tabalinas** [comment]
You could initialize jsSocials for each block specifying the id `$("#mySharing1").jsSocials({ ... `

**Comment by tergra** [comment]
Well you are a genius ahaha... that worked wonders thank you very much !!
