### ISSUE TITLE
dynamic share url support

### ISSUE THREAD

**Issue by saqueib** [tabalinas/jssocials#12]
Thanks for great plugin, I have a list of thumbnails and all have the `jsSocials` attached to them, but I want to make the url of individual thumbnail not the hole page url. Here is my html it has a `data-url` which i wanted to use as share link.

         <div class="sharing" data-url="http://localhost:8000/post/167">
              <img ... />
         </div>

         <div class="sharing" data-url="http://localhost:8000/post/147">
              <img ... />
         </div>

I have initialise plugin like this 

        $(".sharing").jsSocials({
            url : $(this).data('url'),
            showLabel : false,
            shares: ["facebook", "twitter", "pinterest", "googleplus"]
        });

Please help how can I do it.

**Comment by tabalinas** [comment]
Thank you for the feedback!

Try this code:

```javascript
$(".sharing").each(function() {
	$(this).jsSocials({
        url : $(this).data('url'),
        showLabel : false,
        shares: ["facebook", "twitter", "pinterest", "googleplus"]
    });
});
```

**Comment by saqueib** [comment]
Thanks for your quick response, it worked :smiley:
Keep up the great work :+1:

**Comment by tabalinas** [comment]
You are welcome!

**Comment by nawissor** [comment]
Thank you so much @tabalinas ! Works like a charm!

**Comment by tyidnet** [comment]
I am using version 1.4. 

When I try to change share url to a variable, the buttons are no longer showing up. It only works when I use like this - 
url: "http://url.to.share",

I tried the sample code you showed above, same issue.

Any ideas?

thanks!
