### ISSUE TITLE
"downloadable font: download failed" for FontAwesome

### ISSUE THREAD

**Issue by bwmoore22** [tabalinas/jssocials#121]
Firefox web console gets following message:

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: https://www.mydomain.com/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.1

Style sheet shows

@font-face {
	font-family:'FontAwesome';
	src:url(/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.eot?v=4.6.1);
	src:url(/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.eot#iefix&v=4.6.1) format('embedded-opentype'),url(/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.1) format('woff2'),url(/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.woff?v=4.6.1) format('woff'),url(/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.ttf?v=4.6.1) format('truetype'),url(/media/plg_content_jssocials/font-awesome/fonts/fontawesome-webfont.svg?v=4.6.1#fontawesomeregular) format('svg');
	font-weight:normal;
	font-style:normal
}

The path for the font as installed by the plugin is font-awsome/fonts rather than fonts/font-awesome

[mydomain@cpanel fonts]$ pwd
/home/mydomain/www/media/plg_content_jssocials/font-awesome/fonts
[mydomain@cpanel fonts]$ ls
FontAwesome.otf          fontawesome-webfont.svg  fontawesome-webfont.woff   index.html
fontawesome-webfont.eot  fontawesome-webfont.ttf  fontawesome-webfont.woff2

**Comment by Ruud68** [comment]
Hi, this is not jssocials script related but related to my plugin. Please address on my forum :)
https://onlinecommunityhub.nl/forum

**Comment by bwmoore22** [comment]
I posted to the plugin forum; will close this.
