### ISSUE TITLE
Facebook count not working on some URL ? 

### ISSUE THREAD

**Issue by tergra** [tabalinas/jssocials#123]
Hi, 

I'm facing a weird bug. On certain urls the JSsocials Facebook counter doesn't count anything (weird because on the OpenGraph, it does). Example : for url http://urltoshare.com/aabb/ Facebook debugger finds 2 shares / likes / comments : https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Furltoshare.com%2Faabb%2F 
While when retrieved through Jssocials it gives 0. I precise I configured JSsocials well by the way, because if  with the same script I change the url to http://urltoshare.com it works. 

Any idea why this bug ? It's quite impairing unfortunately  :/

**Comment by tabalinas** [comment]
The reason of a different value is that js-socials gets the amount of shares, while in the debugger statistics you see overall value of likes, shares and comments. So this means that this resource has 2 likes (but not shares).

**Comment by tergra** [comment]
It actually has 2 shares, and 0 likes and 0 comments, I know it because I made them myself  ;) So this is not the reason... I tried adding 1 more share and 1 comment for a try but still JSsocials retrieves 0 on Facebook counter, while it should count a total of 4 (3 shares and 1 comment).

**Comment by tabalinas** [comment]
Could it be something fishy about the url itself? For instance, that this url doesn't exist.
In fact, js-socials fetches share count from FB, requesting this url: `https://graph.facebook.com/?id={url}`.
Indeed, for https://graph.facebook.com/?id=http://urltoshare.com it returns `10`.
I've tested it for some urls and it seems to work just fine.
I'm not sure what we can do, since this is FB who is providing this info.
Have you experienced this problem for real urls?

**Comment by tergra** [comment]
Actually Facebook is not supposed to know (or care about the fact that) this url doesn't exist  ;) And yes I've had it on a production website, I just took the easy example above to show you the issue.

The bug may be due to several parameters : 

- no open graph tags on the page, though it is super unlikely that this is the reason
- variables in the url, for instance this url  (http://youflox.com/fr/aabbccdd-fftt-eerr-ssdafffahhh-s-sss/?show_answer=713) is retrieved by FB (1 share and 1 comment, that I made myself) but not by JSsocials which gives 0... Could that be the reason ?

**Comment by tabalinas** [comment]
Yes, it is not supposed to know, but since we have this issue, I just tried to figured out a possible reason.
For this one http://urltoshare.com/aabb/ you don't have any parameters in the url, but it doesn't work. So most probably it's og info.
What's about your production website? Do you have og tags on the page having issues with share count?

**Comment by tergra** [comment]
Yes I have OG on the website I am currently working on. I'm confused because yesterday evening when I tried it was working, and now it no longer does, and I dn't think I have changed anything relevant since then... Could it be that the Facebook counting API is fed up with me asking counts and refreshing the page (which I do for testing purposes) and decides to block the information from being sent to me at some point ?
Actually, on my local test it doesn't work either, while it worked yesterday. I put 2 sets of buttons, each having FB, Twitter, Pinterest and G+1, and none of them retrieves any count (neither the FB / Twitter / Pinterest /G+1 nor the global counter). BUT if I start sharing from the first set of buttons on Facebook, and then refreshes the page, now it actually shows all the shares for both sets of buttons. 

I'm totally lost. But I think this is fairly important to debug this, on the other hand.

**Comment by Ruud68** [comment]
Just to rule out the 'correctness' of the page you are sharing via facebook: https://developers.facebook.com/tools/debug/sharing/

Here facebook tells you what it sees, what is wrong, and you have the possibility to clear the cache that facebook holds for that page.

**Comment by tergra** [comment]
Yes thanks @Ruud68 but I already checked that. So far I am only interested in the number of shares / likes / comments which should be right, not the other og: parameters 

And I think I know the reason : the number of shares appears from time to time, but if I refresh the page several times it totally disappears.  I guess this is either because FB blocks me at some point (remember there are 7 different urls on each of my pages so that could give way to an overload of the API somehow) or Jssocials is not configured to work in this specific condition ?

If this is the first possibility, I'd be interested in knowing if the count is asked to FB on each page load (I think it does) or if there is a specific way of caching JSsocial uses. 

Thank for your answer !

**Comment by tergra** [comment]
(PS : I tried putting 10 sets of buttons with different urls on a simple html page, nothing else, and at the beginning the Facebook counts are retrieved properly, but if I CTRL+F5 to refresh the page several times in the same minute, they disappear, and I get errors in the console :  Failed to load resource: the server responded with a status of 403 (Forbidden)
https://graph.facebook.com/?id=.......). Then if I go with a different IP (from my phone with data and not wifi) they are shown again.

So I am no developer but it seems that this is all due to the Facebook API, right ?  If you are interested I also found the limit you can hit the FB API, here : https://developers.facebook.com/docs/graph-api/advanced/rate-limiting

Any way to bypass this ? Registering a custom API ? Caching ?

**Comment by tabalinas** [comment]
Yes, this is FB API limitation. 
You are right, this can be solved with caching. Since we are talking about page refresh, caching should be done on backend side. Check out my answer to this issue https://github.com/tabalinas/jssocials/issues/120

**Comment by tergra** [comment]
Ok thanks for your answer  ! :)
