### ISSUE TITLE
Put share counts in database

### ISSUE THREAD

**Issue by titounette042** [tabalinas/jssocials#125]
Hi, 

I need to put the share counts in database (the ones from the global counter will do), is there an easy way to do this ? (i.e pass javascript counts into Mysql) ?

Thank you !

**Comment by tabalinas** [comment]
Please take a look at this issue https://github.com/tabalinas/jssocials/issues/19
Use similar approach, but instead of summing up the total count, send an ajax request with the count to the backend to save it to db.
