### ISSUE TITLE
How to center popup iframe?

### ISSUE THREAD

**Issue by jack-fdrv** [tabalinas/jssocials#127]
I have set up my jsSoc with this option
`shareIn: "popup",`
it works perfect, but iframe pop ups in left top corner, I want it be in a center, how to do this?

**Comment by tabalinas** [comment]
You can redefine this sharing strategy or register another one.
Find an example how to do it in docs: http://js-socials.com/docs/#custom-share-strategy.
More info on how to put new windows at the center of the screen on SO: http://stackoverflow.com/questions/4068373/center-a-popup-window-on-screen
