### ISSUE TITLE
custom text not showing on facebook share

### ISSUE THREAD

**Issue by kirankiru** [tabalinas/jssocials#128]
when i add custom text content  in ' **text** ' field. it's not showing up on facebook share.

 $("#share").jsSocials({
    shares: ["facebook"],
    url: "http://url.to.share",
    text: "**this is my custom text which is not showing in fb share**",
    showLabel: true,
    shareIn: "blank"
}

**Comment by Ruud68** [comment]
Facebook doesn't use that text.
Only thing facebook uses is the url.
It then visits the url and fetches all information from that webpage (either via og tags, or via 'logic')

**Comment by kirankiru** [comment]
@Ruud68  thanks for replying. is there any way to show the custom content while sharing facebook ?

**Comment by tabalinas** [comment]
@kirankiru, please checkout the following issue https://github.com/tabalinas/jssocials/issues/8

**Comment by poojarfuturistic5** [comment]
Can anyone able to send the text while sharing with Facebook.
Please help me out...
