### ISSUE TITLE
Title of page coming with white space and new lines as share text

### ISSUE THREAD

**Issue by saqueib** [tabalinas/jssocials#13]
I am getting this strange behaviour, If my page title as some white space and new line, its picking up those and.

      <title>      My cool title with location, New Delhi India 
         &middot; AppName</title>

Now when I am sharing it its showing it like this 

      My cool title with location, New Delhi India 
         · AppName http://localhost:8000/AppName

Since title is generated from PHP backend I am not able to keep it in single line, if jssocial can clean the text a lil will be good

     92.         return $.extend({ url: this.url, text: this.text }, share, shareConfig);

I thing adding .trim() on desct or title should do it

**Comment by tabalinas** [comment]
Thank you for the request! This should be fixed.
