### ISSUE TITLE
Diference between "www.site..." and "site...."

### ISSUE THREAD

**Issue by mtsys** [tabalinas/jssocials#130]
It is some configuration of mine or my mistake, that when sharing the link, does not take from the url the "www"

Link:
https://graph.facebook.com/?id=http://papodealemao.com.br/Blog/Artigo/boteco-maria-coxinha-bar

https://graph.facebook.com/?id=http://www.papodealemao.com.br/Blog/Artigo/boteco-maria-coxinha-bar

Correct use is: "www" or not "www"?

**Comment by tabalinas** [comment]
In fact, both with "www" and without are correct. 
You just need to choose which one you want to use and redirect from another one to the first (to support both options).
See for more info: https://www.sitepoint.com/domain-www-or-no-www/

In you case I guess without "www" is used as default, so just use this one for sharing.
