### ISSUE TITLE
whatsapp link doesnt work

### ISSUE THREAD

**Issue by didididi2** [tabalinas/jssocials#131]
the whatsapp link doesnt work. seems the link layout has changed

**Comment by tabalinas** [comment]
just tested it on my iPhone and it worked just fine.
Could you share more info about the issue you've faced with?

**Comment by didididi2** [comment]
i'm using the demo site link http://js-socials.com/demos/
i'm using a labtop and seems that the desktop whatsapp app must be installed before to work because i'm receiving this message 
![image](https://cloud.githubusercontent.com/assets/24845330/21967081/9afb2046-db80-11e6-944f-fee7594427d8.png)

**Comment by tabalinas** [comment]
Yes, usually WhatsApp is considered to be used on mobile devices. Decision on whether to show this share or not should be taken by the code using plugin.
Probably it makes sense to implement this on the project demo page to avoid this confusion.

**Comment by Ruud68** [comment]
In my plugin (Joomla!)  I am using https://github.com/serbanghita/Mobile-Detect for that.
It enables me not only to differentiate on mobile, but also on tablet and desktop :)
You could also do it using Bootstrap (I think that detection is based on screen resolution)
