### ISSUE TITLE
Fix to Twitter share count 

### ISSUE THREAD

**Issue by tergra** [tabalinas/jssocials#132]
Hi, 

There is an API I've been using to count Twitter shares, their service works well (ignores accounts with very few followers though, in their own words) : New Share Counts. 
You may find an example of count here :
 
http://public.newsharecounts.com/count.json?url=http://js-socials.com/

Documentation : http://newsharecounts.com/done/ 
And some explanations about the way they count shares : http://newsharecounts.com/why-my-twitter-share-counts-are-so-wrong/
 
They don't seem to be willing to turn their API into a paid service (it's donation based which is great, I will definitely donate to them if it works well in the long run), so I guess that's reliable to use their API.

I don't understand how they could count the tweets for JSsocials even if Artem didn't create an account on NewShareCounts.com, but anyway ^^

I tried the folowing code in jssocials.min.js (I kept on purpose the JSsocials URL in, just to see if it works) : 
`twitter:{label:"Tweet",logo:"fa fa-twitter",shareUrl:"https://twitter.com/share?url={url}&text={text}&via={via}&hashtags={hashtags}",countUrl:"http://public.newsharecounts.com/count.json?url=http://js-socials.com/"}`

It doesn't work.  :D Anything I may have done wrong ?

**Comment by tabalinas** [comment]
First, you need to define `getCount` function to read count from the result:

```js
getCount: function(data) {
    return data.count;
}
```

Second, you need to parameterize `countUrl` so that it returns count for required resource, and not for js-socials:

`countUrl: "http://public.newsharecounts.com/count.json?url={url}"`

As for the service, I have not checked how it works, but share count for js-socials should be definitely more than 2, as this service returns.

**Comment by tergra** [comment]
Hi, 

Yes I've done this. What I meant is that, as you can see here : https://jsfiddle.net/9zyL2wsn/4/ 
JSsocials never calls getCountValue in the case of Twitter, it seems.

Any idea why ? 
Thanks for your answer and keep up the good work :)  :)

**Comment by tabalinas** [comment]
It's not called just because `countUrl` is empty for twitter. `getCountValue` is called only when there is a count info returned from the server.

**Comment by lolozere** [comment]
Hi, I work with @tergra 
The countUrl is filled in our example : https://jsfiddle.net/9zyL2wsn/4/ (line 6 of javascript panel).
And the URL ```http://public.newsharecounts.com/count.json?url=http://beastof.com/fr/q/comment-maigrir-simplement-pour-plaire-a-votre-homme/?show_answer=713#answer_713``` return : 
```
{
"url":"https://beastof.com/fr/q/comment-maigrir-simplement-pour-plaire-a-votre-homme/?show_answer=713",
"count":0,
"tracked":0,
"historic":0
}
```
But getCountValue is not called for twitter.

**Comment by lolozere** [comment]
And I have created the getCount function for the share twitter on line 7. But it doesn't work.

**Comment by tabalinas** [comment]
@lolozere: If you open browser console, you see the following message:

```
Mixed Content: The page at 'https://jsfiddle.net/tLxe5nt5/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://public.newsharecounts.com/count.json?url=http%3A%2F%2Fbeastof.com%2F…r-simplement-pour-plaire-a-votre-homme%2F%3Fshow_answer%3D713%23answer_713'. This request has been blocked; the content must be served over HTTPS.
```

Using https instead of http for your count url will fix the issue.

**Comment by lolozere** [comment]
ok thank you very much !!
