### ISSUE TITLE
about issue number 8

### ISSUE THREAD

**Issue by fraferrando** [tabalinas/jssocials#133]
Excuse me
 I've put the tag in the head section of my _Layout.cshtml (MVC Project) but still I can't view the title...
 now the html of my page seems the same of the one of http://js-socials.com/
 can you help me?

**Comment by fraferrando** [comment]
Excuse me
I've put the tag in the head section of my _Layout.cshtml (MVC Project) but still I can't view the title... 
now the html of my page seems the same of the one of http://js-socials.com/
 can you help me?

**Comment by tabalinas** [comment]
Could you provide your website link, to be able to see the html source?

**Comment by fraferrando** [comment]
Yes, thank you
http://quienonsolo.azurewebsites.net/
and this is the article where i'm testing the share with facebook,
http://quienonsolo.azurewebsites.net/Notizia/Index/1

**Comment by fraferrando** [comment]
Excuse me probably now is solved because tryning the link wth the debugger, i can see it properly...
https://developers.facebook.com/tools/debug/
The time of scraping (i don't know what it is) needed to be refresh maybe.

**Comment by fraferrando** [comment]
I confirm, now it works.
I missed to refresh scraping time from facebook debugger.
Sorry to disturb.
Thank you very much.
Francesca
![refresh_scraping_time_from_fb_debugger](https://cloud.githubusercontent.com/assets/25794853/22977900/cf6bc100-f390-11e6-8f01-2e825810b6a9.jpg)

**Comment by tabalinas** [comment]
Glad that it works!
