### ISSUE TITLE
how do I add a custom message in the mail ?

### ISSUE THREAD

**Issue by cornelism** [tabalinas/jssocials#134]
It seems I can only add a subject if I read the docs.

**Comment by tabalinas** [comment]
As you can find in the sources current body is just the shared url: https://github.com/tabalinas/jssocials/blob/master/src/jssocials.shares.js#L8

If you want to set a custom body just redefine the share url like:

```js
jsSocials.shares.email.shareUrl = "mailto:{to}?subject={text}&body=My body value"
```

Important: you have to redefine it before the actual jsSocials widget creation.
