### ISSUE TITLE
Different theme for different div in the same page

### ISSUE THREAD

**Issue by laziaf** [tabalinas/jssocials#137]
I have two different part of my website that contain share button. I want to apply different theme for them. how do I achieve that? From what I've read in documentation, I believe there's not any mathod that can do that. Is there any workaraound to do that?

**Comment by tabalinas** [comment]
Is it on the different page? In this case you could just add different css files (for the desirable theme) to each page.

**Comment by laziaf** [comment]
No, its on the same page

**Comment by tabalinas** [comment]
Then you can edit both themes files you want to use, scoping them with a particular css class. 

```css
/* theme 1 file */
.page-one {
  /* theme 1 css */
}

/* theme 2 file */
.page-two {
  /* theme 2 css */
}
```

Then wrap js-socials grid on each page with a div having necessary class depending on the page.
