### ISSUE TITLE
url without http in twitter

### ISSUE THREAD

**Issue by didididi2** [tabalinas/jssocials#145]
i'm trying to minimize the length of the url so that i can write the maximum ofpermitted words for twitter. so
when i try to write the url without the http in the js initialization function its no more written in the twitter message.
its fine in email, facebook and g+ ... not in twitter. No more url in the message only the text

**Comment by Ruud68** [comment]
twitter does not take in account the http/https in the url because twitter shortens every url by default by itself.
so with or without http(s) does not make any difference in the number of available characters.

**Comment by tabalinas** [comment]
@Ruud68, thanks for the answer.
