### ISSUE TITLE
Could i get a sum of total sharing count of all enabled social network ?

### ISSUE THREAD

**Issue by adrianmak** [tabalinas/jssocials#146]
something like that 
![baidushurufa_2017-6-3_18-22-13](https://cloud.githubusercontent.com/assets/1168716/26752738/9506291c-4889-11e7-8475-e70a169d350e.png)

**Comment by Ruud68** [comment]
here are some instructions on how this could be done: https://github.com/tabalinas/jssocials/issues/90

Would be nice if this functionality could come 'out-of-the-box' :)
