### ISSUE TITLE
could i reset shared count ?

### ISSUE THREAD

**Issue by adrianmak** [tabalinas/jssocials#148]
During development, couple of sharing will be made.
Could I reset the count before putting the pages on live server ?

I found that pages putting on live server are still have the shared count made in development

**Comment by Ruud68** [comment]
No you cannot :(
Sharecounts are not 'remembered' by this script or the website you are using the script on, sharecounts are provided by the platform you shared on.
So when you share urlX on facebook, the count (1) is provided by Facebook. If you would like to reset this to 0 then you should ask facebook :)

**Comment by tabalinas** [comment]
@Ruud68, thanks for the detailed answer!
