### ISSUE TITLE
I receive errors on the console constantly.

### ISSUE THREAD

**Issue by PabloManuel78** [tabalinas/jssocials#150]
```
Uncaught TypeError: Cannot read property 'views' of undefined
    at Object.getCount (jssocials.min.js:4)
    at d._getCountValue (jssocials.min.js:4)
    at d.<anonymous> (jssocials.min.js:4)
    at Object.f (jquery-2.2.2.min.js:2)
    at i (jquery-2.2.2.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.2.min.js:2)
    at z (jquery-2.2.2.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.2.min.js:4)
```

In addition to many other 400 and 403 errors:
```
Failed to load resource: the server responded with a status of 400 ()
cors-anywhere.herokuapp.com/https://plusone.google.com/_/+1/fastbutton?url=…%2F%2Fpruebasphp.com%2Ftienda%2F46291%2Fauriculares-estereo-en-color-negro 

Failed to load resource: the server responded with a status of 403 (Forbidden)
graph.facebook.com/fql?q=SELECT%20total_count%20FROM%20link_stat%20WHERE%20…%2Fpruebasphp.com%2Ftienda%2F46291%2Fauriculares-estereo-en-color-negro%27 

Failed to load resource: the server responded with a status of 400 ()
cors-anywhere.herokuapp.com/https://plusone.google.com/_/+1/fastbutton?url=…%2F%2Fpruebasphp.com%2Ftienda%2F46291%2Fauriculares-estereo-en-color-negro 

Failed to load resource: the server responded with a status of 403 (Forbidden)
```
![image](https://cloud.githubusercontent.com/assets/5701864/26834451/b12e047c-4ad5-11e7-96a6-088c3d9ad167.png)

**Comment by Ruud68** [comment]
Do you have enabled the 'do not track' functionality or a blocker of some kind?

here is detailed description of problem and why this is happening: https://onlinecommunityhub.nl/forum/jssocials/64-jquery-js-look-error

**Comment by PabloManuel78** [comment]
I do not think it's because of my browser. The same thing happens to me in Firefox. The previous example was Chrome:
![image](https://user-images.githubusercontent.com/5701864/26866141-2c13f4b4-4b60-11e7-8f20-ca149410ee5f.png)
Here the error is more specific:
```
XML read error: syntax error

Location:

Https://cors-anywhere.herokuapp.com/https://plusone.google.com/_/+1/fastbutton?url=http%3A%2F%2Fpruebasphp.com%2Ftienda%2F46159%2Fturntable-stylus

Line number 1, column 1:
```

I think the error is in the url that are used. Here are the errors returned by URLs:

**https://graph.facebook.com/fql**
```
{
   "error": {
      "message": "(#12) fql is deprecated for versions v2.1 and higher",
      "type": "OAuthException",
      "code": 12,
      "fbtrace_id": "G90Cm/qPbLo"
   }
}
```

**https://cors-anywhere.herokuapp.com/https://plusone.google.com/_/+1/fastbutton**
```
Missing required request header. Must specify one of: origin,x-requested-with
```
**https://cors-anywhere.herokuapp.com/https://plusone.google.com/_/+1/fastbutton**
```
https://cors-anywhere.herokuapp.com/https://plusone.google.com/_/+1/fastbutton
```

**Comment by Ruud68** [comment]
Hi, here some info for the Google errors: https://github.com/tabalinas/jssocials/issues/92

**Comment by PabloManuel78** [comment]
Sorry. You can close the case. I upgraded to 1.5.0 and no errors appear on the console anymore.
