### ISSUE TITLE
Sharing custom image

### ISSUE THREAD

**Issue by GhostPengy** [tabalinas/jssocials#151]
I have come across a little pickle. Everything works fine and dandy. However, a client wants a gallery and share the specific image what is currently open in lightbox. That open image should be also the image what appears on the share link. I have been searching for a solution to no avail. Is there a solution I have missed or something? Basically, I need to pass the image parameter somehow.

**Comment by Ruud68** [comment]
Hi, only PinIt has the option to specify an image that should be shared (for PinIt the image is the content).
Facebook, Twitter, Linkedin, Googleplus etc. do not take an image as argument but they fetch the image themselves: first they trying to use the og:image metatag and if that is not found they will try the first available image with minimum size requirements.

So if you want to share a specific image on your page then you should have a og:image metatag for that image on your page.

generating metatags is not part of this script.

**Comment by tabalinas** [comment]
@Ruud68, thanks for the great answer!

**Comment by sabrina4483** [comment]
It seems possible to share specific image on your site to social medias by using jssocials.
I've tried to upload images to a specific folder into the site (cpanel) and changed its permission to 755.
By using jssocials, specify the url to the image, eg: www.test.com/testfolder/test.jpg
with this, able to share the image on facebook as a link.
