### ISSUE TITLE
Hot to put a </br>

### ISSUE THREAD

**Issue by siupud** [tabalinas/jssocials#154]
Hello
Thanks for this plugin 
How to change the *.js to put a `</br>` between text and url when we clik for example to the icon tweet
thanks and best regards

**Comment by tabalinas** [comment]
Redefine twitter sharing url:

```js
jsSocials.shares.twitter.shareUrl = "https://twitter.com/share?url={url}&text={text}%0a&via={via}&hashtags={hashtags}"
```
