### ISSUE TITLE
Text value is only appended on twitter

### ISSUE THREAD

**Issue by eleonorsomosot** [tabalinas/jssocials#155]
Is there any way that the value of text option be automatically put to share fields of other social media?

**Comment by Ruud68** [comment]
I don't think that is possible. for e.g. facebook, linkedin , google+ > they visit your site and take the text from the og: tags on your page. If not present they will default to meta description. Only thing you can 'push' to these platforms is the url.

**Comment by eleonorsomosot** [comment]
Ah I see. Thank you for explaining it to me and for the super quick response. 👍
