### ISSUE TITLE
Share image of a given URL on Social Network - possible?

### ISSUE THREAD

**Issue by NineNineNineIonoSpheres** [tabalinas/jssocials#156]
Hello,

I am trying out Jssocials. Right now, when I click "Facebook Like" button, the image being shared is the first image on the site, but I would like another image to be in its place. 

Is it possible to make it so that the share includes and displays an image (of a given URL in Javascript) to the social sites? Does jssocials have that functionality?

Iono

**Comment by Ruud68** [comment]
In short: not possible
https://github.com/tabalinas/jssocials/issues/151
