### ISSUE TITLE
Personalized mail body

### ISSUE THREAD

**Issue by stefef** [tabalinas/jssocials#157]
Hi Tabalinas,

Great job this lib !
I'm interested to personalize the mail body with html content.
I'm actually building a custom mail (html with text and image content) from a JSON object. I'm using Javascript/JQuery to build the body content in a variable.
I read the anwser you wrote for this issue (https://github.com/tabalinas/jssocials/issues/134) but, unforunately, it is just working with simple text; directly whitout variable.
Sharing action did not finish successfully with a variable define for the body.

Also, do you think it sould be possible to add a new share option to print an html content (media+-html-text) ? 

Did you see a way to solve these issues ?
By advance, many thanks for your help.
Stef

**Comment by tabalinas** [comment]
Hi Stef,

Have you tried to set `jsSocials.shares.email.shareUrl` and reinit the widget when the variable is changed?

**Comment by stefef** [comment]
Hi Tabalinas,

Thanks for your answer.

Yes, I've tried to set the shareUrl and init the witget.
But, finally, I don't know if my problem can be solved.

You can find a piece of my code....

TEST 1 => below you can see a variable which is containing plain text : It work's fine !
```
var mail = "Lorem ipsum ... Lorem ipsum ... Lorem ipsum ... Lorem ipsum ... "; 
var toShare = 'mailto:{to}?subject=my subject&body=' + mail;
jsSocials.shares.email.shareUrl = toShare;
```
TEST 2 => Here you can see I try to insert HTML content in the mailbody, It works like plein/text, because (I think) all the header of an HTML mail is not interpreted by jquery as it can be with the mail() php function or with a shell script injecting an html file to the sendmail command...
But maybe I'm wrong !
```
var toShare = 'mailto:{to}?subject=my subject&body=<html><head /><body>toto</body></html>';
jsSocials.shares.email.shareUrl = toShare;
```
TEST 3 => This way work fine too !
```
jsSocials.shares.email.shareUrl = "mailto:{to}?subject=My mail subject&body=toto";
```

```                    
$("#share").jsSocials({
  shareIn: "popup",
  showLabel: false,
  showCount: "inside",
  shares: [
   {
     share: "email",
     logo: "fa fa-envelope",
     label: "Envoyer",
     showCount: true,
     to: "",
     shareIn: "self"
   },
   {
     share: "facebook",
     logo: "fa fa-facebook", 
     label: "Partager",
     showCount: true,
     shareUrl: "https://www.facebook.com/sharer/sharer.php?&u=http%3A%2F%2Fgoogle.fr"
   },
   ]});
```

Maybe you know a way to send full HTML content by mail (with a picture in the mailbody, for example) using the mail share function of jsSocials which is for me a powerfull widget.

By advance, thank you for your help.

Stef

**Comment by tabalinas** [comment]
You are right, this is not possible https://stackoverflow.com/a/13415988/1140893
