### ISSUE TITLE
Img on Facebook

### ISSUE THREAD

**Issue by fvenuto** [tabalinas/jssocials#158]
Hello.
Can someone help me to figure out why on this page the image is not showing on facebook sharing?
http://blackliterecords0.exeq.me/bao

On that one is working:

http://blackliterecords0.exeq.me/spacetimeboulevardstoptwo

**Comment by Ruud68** [comment]
you set the image for facebook with the og:image metatag.
On both pages this is not correct.
It should be like:
```
<meta property="og:image" content="https://onlinecommunityhub.nl/images/opengraph/image-8-tc.jpg" />
```
you can view what is set in the page source, just search for og:image
setting these meta tags is NOT part of the jssocials script.

**Comment by tabalinas** [comment]
@Ruud68, thanks for the detailed answer!

**Comment by fvenuto** [comment]
Hi. Thanks for the help.
I didn't told that i tried also using the meta tag.
But if you look at the page:

http://blackliterecords0.exeq.me/bao there's the image in the head part but the plugin is still getting the white icon of soundcloud as image to share. 

Is there a way to set the image on meta as more important than others? Also if there's a better image that fit the requirements in the page.

<img width="531" alt="schermata 2017-07-10 alle 11 16 25" src="https://user-images.githubusercontent.com/22097109/28011037-470eeb28-6561-11e7-9c77-23b09bb4c219.png">
<img width="1621" alt="schermata 2017-07-10 alle 11 05 40" src="https://user-images.githubusercontent.com/22097109/28011051-52c6d0e8-6561-11e7-95bd-289827620614.png">

**Comment by Ruud68** [comment]
it displays just fine (from facebook development tools):
![image](https://user-images.githubusercontent.com/2733197/28027498-875020ca-6599-11e7-8e3c-46643275204f.png)

**Comment by fvenuto** [comment]
I've tried the same :D 
So i'll check where can be the problem...

<img width="1011" alt="schermata 2017-07-10 alle 18 15 09" src="https://user-images.githubusercontent.com/22097109/28028101-bc9942aa-659b-11e7-8954-89d53ba063f1.png">
