### ISSUE TITLE
Dynamically append social channel to shared urls

### ISSUE THREAD

**Issue by ErinBaker** [tabalinas/jssocials#159]
Would be great to be able to dynamically add the social channel clicked as utm_source or other parameter to the URL so returning traffic has an acquisition source.

ie. Click Twitter share and the url `example.com?utm_source=%share%` becomes `example.com?utm_source=twitter`

**Comment by tabalinas** [comment]
Redefine `shareUrl` of the share to include `utm_source=%share%`.
See an example: https://jsfiddle.net/tabalinas/5g4dLwy5/
