### ISSUE TITLE
Popup instead new page

### ISSUE THREAD

**Issue by mojpe** [tabalinas/jssocials#16]
It is possible to configure popup on click instead of opening in share in new page (tab)?

Thank you in advance

**Comment by tabalinas** [comment]
There is no build-in option for that. I'll consider it in the future.
Now try to use the following a little tricky workaround:

```javascript
$("#share").jsSocials({
    _getShareUrl: function() {
        var url = jsSocials.Socials.prototype._getShareUrl.apply(this, arguments);
        return "javascript:window.open('" + url + "', 'Sharing', 'menubar=no')";
    },
    shares: ["twitter", "facebook"]
});
```

Of course, you can set any window params you prefer.

**Comment by mojpe** [comment]
Thank you that was really helpful :)

**Comment by tabalinas** [comment]
You are welcome!

**Comment by saqueib** [comment]
Any news when it will be available the popup window.

```
_getShareUrl: function() {
            var url = jsSocials.Socials.prototype._getShareUrl.apply(this, arguments);
            return "javascript:window.open('" + url + "', 'Sharing', 'menubar=no,width=500,height=500')";
        },
```

I have used your solution but in FF its opening popup with a tab url `javascript:window.open('...')`;

But same works in Chrome

**Comment by tabalinas** [comment]
Make the FF work is harder for that case. You have to do the following:

```javascript

// external func to open share window
window.openShareWindow = function(url) {
    window.open(url, 'Sharing', 'menubar=no,width=500,height=500');
};

$("#share").jsSocials({
    _getShareUrl: function() {
        var url = jsSocials.Socials.prototype._getShareUrl.apply(this, arguments);
        return "javascript:window.openShareWindow('" + url + "');";
    },
    shares: ["twitter", "facebook"]
});

// remove target attr
$("#share").find("a").removeAttr("target");
```

It should help.

**Comment by uliworm** [comment]
Doesn't work for me. A new tab opens (no popup) and this tab even remains empty.
A popup would be nicer, so also hope it will be implemented in the future. Until then i will wait, it's not too urgent :)

**Comment by gvanto** [comment]
(Firefox) I found that the popup worked but then the current window would go to 'javascript:window.openShareWindow( ... '

to avoid this I put:

`// external func to open share window
window.openShareWindow = function(url) {
    window.open(url, 'Sharing', 'menubar=no,width=500,height=500');
    void(0);
};`

Which works can try it on [http://foundationize.com](http://foundationize.com) 
Although the counts don't seem to work on the button, even though they do seem to be correct:
https://graph.facebook.com/fql?q=SELECT%20total_count%20FROM%20link_stat%20WHERE%20url=%27foundationize.com%27

**Comment by Ruud68** [comment]
#49 ?

**Comment by tabalinas** [comment]
Implemented in https://github.com/tabalinas/jssocials/pull/49
