### ISSUE TITLE
Dynamically setting share text and url on social  click

### ISSUE THREAD

**Issue by sashberd** [tabalinas/jssocials#161]
I saw the answer of #65 , and it is good for me, but not enough.

Is there is an option to setup share link and share text on social click.
I had tried to do this via `on: click:function(ev){}`, but after reviewing you code I saw that you bind click to <a> tag and after this is you bind all `on` options event functions

I think it is better to change such behavior: first bind all `on` options and after the <a> default click

This, also in my case, could give to user option to change/edit share URL and text dynamically
Before I will do changes locally to you great library, I would like to ask you if this idea is good and you will change the behavior.

**Comment by tabalinas** [comment]
Since share strategy creates sharing link it's not possible to change handlers order.
But you can redefine share strategy. 
The docs describes how to register new custom share strategy http://js-socials.com/docs/#custom-share-strategy.
In your case instead of defining a new one you can redefine the existing (`popup` in your case, I guess, since this is the only one using click handler)

**Comment by simogeo** [comment]
Hi, same situation here.

I've read about the custom-share-strategy, style, I'm not able to set url dynamically. I'm trying to pass my url on init but onlaso on lcik with shareUrl with no effect. Here is my code. What's wrong ? 


```
jsSocials.shareStrategies["my_popup"] = function(args) {
        return $("<div>").click(function() {
                window.open(args.shareUrl, "MyShareWindow", 
                    "width=800, height=600, location=1, resizeable=1, menubar=0, scrollbars=0, status=0, titlebar=0, toolbar=0");
            });
    };
    
    $("#share").jsSocials({
        shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest", "stumbleupon", "whatsapp"],
        showLabel: true,
        text:$('title').text(),
        showCount: true,
        shareUrl: $('#input-current-url').val(),
        shareIn: "my_popup",
        url: $('#input-current-url').val(),
        on: {
            click: function(e) {
            	shareUrl: $('#input-current-url').val() 
            },
            mouseenter: function(e) {},
            mouseleave: function(e) {}
        }
    });
```

Thanks for your help !
