### ISSUE TITLE
i have a questions

### ISSUE THREAD

**Issue by shlomialon** [tabalinas/jssocials#168]
![image](https://user-images.githubusercontent.com/21358576/30163669-74a84142-93e2-11e7-9c52-98f6c43f6347.png)

**Comment by tabalinas** [comment]
1. Yes, in the demo you can see how we share google url instead of the current url.

2. I think you are talking about this https://github.com/tabalinas/jssocials/issues/158

3. Not sure what you mean here.

**Comment by AfaMadza** [comment]
Hi,
I'm trying to add round share icons to a website on my server that I access via SSH. I'm currently using the jsSocials CDN, but I'm having trouble making the icons round because I can't edit the jsSocials.css file. Any help would be greatly appreciated.
