### ISSUE TITLE
Problem creating multiple instances

### ISSUE THREAD

**Issue by rfh96** [tabalinas/jssocials#172]
Problem creating multiple instances jssocails due to if we pass  dynamic id.

that is my code 
```html
<script type="text/javascript">
		 $(".my-socials-sharing-<?php echo $row['id']; ?>").jsSocials({
		 url: "http://thisishrmedia.com/",
		 text: "This is hr media",
		 showLabel: false,
		 showCount: "inside",
		 shares: ["twitter", "facebook", "googleplus", "linkedin"]
	});
	 </script>
	
	 <div class=" my-socials-sharing-<?php echo $row['id']; ?>"></div>
```
and if we not pass the id one instance created.

**Comment by tabalinas** [comment]
Creating multiple instances is supported.
Looks like the reason is that your script executed right away by the element is located below, so jssocials is not created.
Just put your `div` above the script.
