### ISSUE TITLE
Shared count on facebook

### ISSUE THREAD

**Issue by umeshkafle** [tabalinas/jssocials#175]
Hello,
I have used your plugins in my Rails apps, I can share it to Facebook, Twitter, linkedin and Google plus but the problem is I want the share count in each of the Social media. However I have found that Twitter and Google plus are not showing share count while doing research in **jsSocials** but still the same problem has seen in Facebook and Email whereas linkedin works fine. Is there any updated solution for this?

**Comment by Ruud68** [comment]
Twitter will never work: they pulled the end-point of the market some (long) time ago.
here is some info on Google+ not working: https://github.com/tabalinas/jssocials/issues/92
Facebook however is working perfectly on my sites: no issue here.

**Comment by tabalinas** [comment]
@Ruud68, thanks for the detailed answer!
