### ISSUE TITLE
How to dynamically add "on" click using the option?

### ISSUE THREAD

**Issue by melloware** [tabalinas/jssocials#176]
Sorry for the question but what I want to do is add another click handler at run time using the option like...

`$("#share").jsSocials("option", "on", ????);`

I wasn't quite sure the syntax to add a new javascript method for click using the "option" or whether that was even the correct way to do it?

**Comment by tabalinas** [comment]
If you don't define `on` option, then you can do:
```js
$("#share").jsSocials("option", "on", { click: function() { ... } });
```

if `on` option has been defined, read it first and extend with `click`.

You could also use `$.callbacks`. It will be fired inside the single `click` handler and you can add new handlers any time later:

```js
var jsSocialsClick = $.Callbacks();
...

on: {
  click: function() {
     jsSocialsClick.fire();
  }
}
```

**Comment by melloware** [comment]
Thank you!
