### ISSUE TITLE
Twitter & Google+ count not working

### ISSUE THREAD

**Issue by TLWebdesign** [tabalinas/jssocials#177]
Hi,

I have an issue where the counts for twitter and Google+ are not working it seems. The urls have been shared on both networks but not showing up.

URL: https://www.coslimburg.nl/cos-actueel/277-fairtrade-week-in-heerlen-en-sittard-geleen.html

**Comment by Ruud68** [comment]
Hi, Twitter stopped providing these counts a long time ago: https://onlinecommunityhub.nl/community-tools/goodbye-twitter-counter

There is an issue with Google plus, that cannot be fixed. If you search here, you can find what it is and what a workaround would be.
