### ISSUE TITLE
Formatting of "mailto" URL?

### ISSUE THREAD

**Issue by arothmanmusic** [tabalinas/jssocials#178]
When using the "Email" share, the format of the link is:

mailto:?&body=http://my.url

The ampersand between ? and body is not accepted by MS Outlook and it generates a blank email. Thunderbird doesn't seem to mind it, but Outlook simply launches an empty email.

**Comment by tabalinas** [comment]
Why do you put ampersand? Have you tried w/o it?

**Comment by arothmanmusic** [comment]
I don’t have any control over how the script generates the link… do I?

I ended up adding an additional script to remove the & again after
jssocials runs.

Drew

**Comment by tabalinas** [comment]
Ah, I see, you are right, it's because you don't define a `subject`.

but you can redefine the share url of the `email` share (before you initialize the jssocials control):

```js
jsSocials.shares.email.shareUrl = "mailto:{to}?body={url}";
```
