### ISSUE TITLE
Regarding facebook , linkdein , twitter sharing button not working.

### ISSUE THREAD

**Issue by rfh96** [tabalinas/jssocials#180]
facebook , linkdein , twitter button not sharing the content  properly , facebook , twitter  pulling the unknown data but linkdien not sharing proper post.
Here is my website url
http://happyhoursfood.com/booking/profile/12

you can check.

**Comment by tabalinas** [comment]
Everything seems to be working as expected:
twitter - you defined `text: ""`, so no text displayed.
facebook - to declare info for sharing, you need to provide open graph tags (https://developers.facebook.com/docs/sharing/webmasters#markup)
linkedin - seems to be working fine.
