### ISSUE TITLE
Add new function in shares

### ISSUE THREAD

**Issue by NewbieHphp** [tabalinas/jssocials#20]
hello there!

i am new in doing web programming. Can i know is that anyway to add in new function into the shares. Say, when i click on the facebook button, i want to save something into my database or just simply alert something.

Thanks :)

**Comment by tabalinas** [comment]
Good point. Currently there is no straightforward way to add a callback on share action.

For now you can redefine the `_createShareLink` function:

```javascript
$("#share").jsSocials({
    _createShareLink: function(share) {
        var $result = jsSocials.Socials.prototype._createShareLink.apply(this, arguments);
        $result.on("click", function() {
              // your action here
        });
        return $result;
    },
    shares: ["twitter", "facebook"]
});
```

**Comment by NewbieHphp** [comment]
Hi again,

Another question...say like i want to append some QueryString into shareURL after onClick action, is that possible?

Example:

My page URL is "http://myWebsite.com". 

After click on the Facebook Share button, i want the share URL to be: "https://www.facebook.com/sharer/sharer.php?_rdr=p&u=http://myWebsite.com?shareByID=1"

**Comment by tabalinas** [comment]
Try the following:

Set a placeholder to the sharing url like `_url_` and in click handler replace the `href` of the link.

```js
// init jssocials
$("#share").jsSocials({
    url: "_url_",
    _createShareLink: function(share) {
        var $result = jsSocials.Socials.prototype._createShareLink.apply(this, arguments);
        $result.on("click", function() {
              // replace the your placeholder with actual url
              var href = $result.attr("href");
              $result.attr("href", href.replace("_url_", actualUrl);
        });
        return $result;
    },
    shares: ["facebook"]
});
```

**Comment by NewbieHphp** [comment]
Thanks for the reply!

I apply the code but it only work when i click on the button for the SECOND time. When the first click, the shareURL will be the default URL "https://www.facebook.com/sharer/sharer.php?_rdr=p&u=_url_".

```javascript
 $("#share").jsSocials({
        url: "_url_",
        _createShareLink: function(share) {
                  var $result = jsSocials.Socials.prototype._createShareLink.apply(this, arguments);
                  $result.on("click", function() {
                                    $.ajax({
                                          url: '<?php echo site_url('/home/first'); ?>',
                                          data: { userid: "DummyData" },   
                                          type: 'post'
                                          }).done(function (data) {
                                            var href = $result.attr("href");
                                            var SharebyUrl = window.location.href + "?shareBy=" + data;
                                            return  $result.attr("href", href.replace("_url_", SharebyUrl ));
                                         });
                 });
                 return $result;
           },
 });
```

**Comment by tabalinas** [comment]
Check out the following answer on SO http://stackoverflow.com/questions/16425260/changing-a-links-href-after-click-with-jquery
