### ISSUE TITLE
Customizing output

### ISSUE THREAD

**Issue by ildaroit** [tabalinas/jssocials#23]
Hi! 

1. How can i divide 8 logos output to two rows with 4 logos on each?
I anderstand its possible to make throw div1.jsSocials and div2.jsSocials but in large screen i need 2 rows in phones 1 row..

2. And when a minimize screen - icons not aligned by cell - one icon not exactly under up icons.

3. And one more q: how can i add to class jssocials-share my own classes?

**Comment by tabalinas** [comment]
1. You can limit the width of the js-socials div with css `width` property. Then shares that won't fit in this width will go to the second line.

2. Could you bring more details about the issue? An image or js-fiddle would be good.

3.  Share has an option `css` https://github.com/tabalinas/jssocials#css-string, which allows to specify custom css class for the share.
