### ISSUE TITLE
Refuses to execute LINKEDIN script

### ISSUE THREAD

**Issue by AnyaSmol** [tabalinas/jssocials#231]
I see this error in all major browsers (Chrome, FF, Safari):
_GET https://www.linkedin.com/countserv/count/share?format=jsonp&url=http%3A%2F%2Fjs-socials.com%2F&callback=jQuery111305995814710524587_1561995096895&_=1561995096897 net::ERR_ABORTED 404_

**Chrome:**
![Screen Shot 2019-07-01 at 8 39 00 AM](https://user-images.githubusercontent.com/52419358/60449069-b6e33f00-9bdb-11e9-9dab-00bf293b5287.png)

**FF:** 
![Screen Shot 2019-07-01 at 8 40 11 AM](https://user-images.githubusercontent.com/52419358/60449198-f1e57280-9bdb-11e9-9b1a-508550199306.png)

BTW, I didn't see the error last week.

**Comment by Ruud68** [comment]
https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter
Linkedin stopped some time ago with this API end point

**Comment by AnyaSmol** [comment]
Yes, I have already seen this. Meant to post an update. I removed a link to the share count page from my js files. Thanks for the quick response!
