### ISSUE TITLE
Updating an option doesn't refresh the links

### ISSUE THREAD

**Issue by nicolasbinet** [tabalinas/jssocials#25]
When I'm updating an option with the so called method, the social links don't get refreshed.

```
$social.jsSocials("option", "url", newUrl);
```

The refresh method does refresh the code, but as the new option value is not pushed to the "shares" object, the shared link doesn't get refreshed.

A working option method looks likes this for me.

```
option: function(key, value) {
    if(arguments.length === 1) {
        return this[key];
    }

    this[key] = value;

    $.each(this.shares, function(idx, share) {
        share[key] = value;
    });

    this.refresh();
}
```

Comments are welcome.

**Comment by tabalinas** [comment]
You are right, this is critical issue. The problem actually takes place with two options `url` and `text`, that are provided to the shares from jsSocials. Maybe it also means that it would be convenient to have method to set option of particular share, like `shareOption('shareName', 'optionName', 'optionValue')`.

Thank you for the report!
