### ISSUE TITLE
Twitter count endpoint

### ISSUE THREAD

**Issue by eranshmil** [tabalinas/jssocials#27]
As described in the following post, the urls count endpoint is not available anymore since 20th November. So there's no way to show tweets of the url.

https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

**Comment by eranshmil** [comment]
I created a pull request to remove that.
https://github.com/tabalinas/jssocials/pull/28

**Comment by tabalinas** [comment]
Yes, unfortunately it's true. 
Thank you for PR!
