### ISSUE TITLE
Twitter not show count (count.json)

### ISSUE THREAD

**Issue by Mdiaw2550** [tabalinas/jssocials#29]
Hi, twitter not show count.

Can you help me. 
Thank you.

Error: Failed to load resource: the server responded with a status of 404 (Not Found)
/**/jQuery11110980863899923861_1448271148530({"errors":[{"message":"Sorry, that page does not exist","code":34}]});

https://cdn.api.twitter.com/1/urls/count.json?url=urltest&callback=jQuery11110980863899923861_1448271148530&_=1448271148531

**Comment by eranshmil** [comment]
https://github.com/tabalinas/jssocials/issues/27

**Comment by tabalinas** [comment]
Mdiaw2550, it's not possible (since 20th of November) to get Twitter shares count. Now it's possible only with native twitter share button. Sorry.

**Comment by brugeman** [comment]
Hi, tabalinas, can I offer newsharecounts.com as an optional alternative to the shut down API? It requires user to sign-up with their Twitter account and specify the website, and than share counts are tracked and can be fetched from public API.

**Comment by Ruud68** [comment]
one of the big drivers for using jssocials is the fact that my website doesn' t have to do external calls to scripts that I cannot control, that use my visitors click and share behaviour and that I have to explain to my users why I am sharing their data with third parties. And probably it will slow down my site.
for me that doesn' t weight up to having the count.

just my 2 cents :)
