### ISSUE TITLE
Mobile devices detection > private messaging > whatsapp

### ISSUE THREAD

**Issue by Ruud68** [tabalinas/jssocials#30]
Hi, really love your script and I am currently working with it in a Joomla website.
I am currently investigating to implement private messaging (e.g. whatsapp).
This is possible with your script, but one functionality is missing that could come in handy.

Whatsapp is only available on mobile devices, so it would be really cool if it didn't show up on eg tablet or desktop.

Not sure if mobile device detection should be part of your script but maybe this is an idea that you could work with? Love to hear your thoughts on this!

Thanks a lot for sharing your amazing work with the world :)

**Comment by tabalinas** [comment]
Hello! 
Thank you for the pleasing feedback!
I think device detection is really another topic and is not related that much to the plugin. I believe the best solution would be initialize widget conditionally according to the device type. And device type will be defined based on UserAgent string.

**Comment by Ruud68** [comment]
Hi, thanks for your answer. I will follow that route. Doing the same for pinterest button: when there is no image on the page, do not display the pinterest button (because otherwise you will end up with an error). Same 'logic' could be applied to the whatsapp button.

**Comment by tabalinas** [comment]
You are welcome! Thanks for your interest and feedback!
