### ISSUE TITLE
WhatsApp question(s)

### ISSUE THREAD

**Issue by Ruud68** [tabalinas/jssocials#32]
Hi, been trying to get whatsapp as part of one of the buttons and run into the following 'issue'.
the whatsapp url only has 1 parameter: 'text', but sending only text is not usefull when you are sharing a webpage :)

I have the following code in the jssocials.js:
```
        whatsapp: {
            label: "WhatsApp",
            logo: "fa fa-whatsapp",
            shareUrl: "whatsapp://send?text={text}",
            countUrl: ""
        },
```
What I want to do is sent the text AND the url, but your script doesn't parse that correctly...
shareUrl: "whatsapp://send?text={text} {url}", > doesn't work > result is "this is my article text {url}"
shareUrl: "whatsapp://send?text={text} ={url}", > doesn't work > result is "this is my article text ={url}"
shareUrl: "whatsapp://send?text={text}&url={url}", > url gets constructed, but whatsapp chokes on it :( > result is "this is my article text&url=https://...."

what I am now doing as a workaround is to construct the text + url in php and parse this to the jssocials script
{ share: "whatsapp", text: "this is my article text https://andthismyurl"},

so the question is, is it possible to parse the url via the jssocials.js script without the "&url="?

question 2: can I do a PR for my changes to the .css and .js files for adding whatsapp?

**Comment by tabalinas** [comment]
Hi, I see the problem. Indeed, in the url only `param={value}` are replaced. But it's easy to change this. 
Feel free to make a PR, and after it, I'll improve url substitution.

**Comment by Ruud68** [comment]
Thanks @tabalinas , just created PR #33 
I set the text= to {url}  because that is what you want to share. When WhatsApp opens on your mobile, the url is already in your text fiiels and WhatsApp handles the link. Before pressing the sent button you can type your own text.

Would be nice if the title of the webpage could be part of the message automatically, but as I am no developer I have no clue how to change that param={value}  part :)

Hope this helps! Open for feedback!

**Comment by tabalinas** [comment]
I've implemented partial url params replacement. Could you change the sharing url of Whatsapp app and check whether iit works as expected?
Thank you!

**Comment by Ruud68** [comment]
Hi, thanks for your change :)
I have set the following in jssocials.js
```
        whatsapp: {
            label: "WhatsApp",
            logo: "fa fa-whatsapp",
            shareUrl: "whatsapp://send?text={url} {text}",
            countUrl: ""
        },
```
in my php script I call whatsapp with:
```
{ share: "whatsapp", text: "'. $title .'"}
```
where title is the page title opposed to leaving it empty and getting the meta description :)

this works like a charm!
whatsapp opens, you select the person you want to share with, and the message is prefilled with url (first) and text (in my case $title)... user can then add or change text and press send.

so with the additional change of the whatsapp part in jssocials I think this is ready to go :)

**Comment by tabalinas** [comment]
Could you make a PR for Whatsapp?

JFYI: by default as a sharing text if `<meta name="description" content="...">` is not specified the page `<title>` is used.
This is the source code:
```js
this.url = window.location.href;
this.text = $.trim($("meta[name=description]").attr("content") || $("title").text());
```

**Comment by Ruud68** [comment]
Hi, I will. just setting up grunt so I can create new version with changes in it (I am new to all this :))

I know that if meta description is is empty the title is used, but that when you e.g. tweet, a metadescription of 250 characters is to long (limit of 140 characters in total incl. (shortened) url, so you still want the title instead.

That is why I call the tweet also with $title in my php, same for whatsapp :)

**Comment by Ruud68** [comment]
the grunt master :) just did a PR for the whatsapp change.
(a whole new world has opened for me :)))
