### ISSUE TITLE
whatsapp issue on some mobile browsers

### ISSUE THREAD

**Issue by Ruud68** [tabalinas/jssocials#44]
Hi,
more and more people are using my Joomla plugin that displays the jssocials buttons on Joomla content pages.
Thats is good news... but I recently ran into an issue with a user where the whatsapp button didn't work.
As it turned out this user was running a specific browser for android and clicking the button resulted in a page not found error.
At first I thought it was an issue with his specific browser as using stock browser or firefox on his device did work.
Then he provided me with a website with whatsapp button that worked perfectly for his browser...

Did some digging and found the culprit in the way jssocials constructs the href for whatsapp (and for all buttons as that is a generic function)

According to whatsapp documentation (https://www.whatsapp.com/faq/nl/android/28000012) the url should be constructed as follows:
```
<a href="whatsapp://send?text=Hello%20World!">Hello, world!</a>
```
The way jssocials constructs this url is with target="_blank"

That is when it goes wrong... when omitting the target part from _createShareLink: function(share)
It works okay, but then there is the issue that the buttons (twitter, linkedin, facebook, etc.) do not open in a new window but override the current window.
For twitter, facebook, etc a new browser window should be opened as that is where the action takes place, for whats app a new window should not be opened: clicking the url kicks off the start of the app.

As I am not a JavaScript hero :) I was wondering if the target="_blank" part could be configured / toggled?

**Comment by tabalinas** [comment]
Yes, we can add a special parameter to shares for this.

**Comment by Ruud68** [comment]
Hi, this is good news :)
What I noticed when testing is that the current solution takes some seconds to open the whatsapp app via eg. firefox. When opening without the target="_blank" this is much faster... so although firefox opens the app correct it has some kind of failsave built-in that not all browsers have.

If you have something for me to test, please let me know :)

**Comment by tabalinas** [comment]
Sure. Thank you for the report.

**Comment by Ruud68** [comment]
Hi, did some more digging into how to possibly 'fix'.
I have tried with the following urls:
```
<p><a href="whatsapp://send?text=Hello%20World!" target="_blank">Hello, world! (target= new window)</a></p>
<p><a href="whatsapp://send?text=Hello%20World!" target="_self">Hello, world! (target= current window / frame)</a></p>
<p><a href="whatsapp://send?text=Hello%20World!">Hello, world! (target= not set)</a></p>
```
The target="_blank" FAILS
both the target="_self" and omitting the target (third use case) WORKS

This is a (android) browser that you can test with: https://play.google.com/store/apps/details?id=com.ksmobile.cb

Hope this helps :)

**Comment by Ruud68** [comment]
Hi, I have created a fix for this. the fix extends the jssocials script with a 'target' (='_blank|_self') parameter tog-gable per share. It defaults to the current _blank.

The problem is 'bigger' then initially encountered and probably not only limited to whatsapp (but all mobile apps > link as well?).
1. some (exotic) browsers do not start the mobile app when opening the url in _blank window / tab
2. when the mobile app is triggered and closing the app returns you to an empty window / tab instead of to the page you pressed the button from

Using _self tackles both problems.

I have it currently in test here: https://onlinecommunityhub.nl/ (via mobile browser > whatsapp button)

If tests are okay I will do a PR.

Thought I'd share it here in order to avoid somebody else working on this :)
regards,
Ruud.
