### ISSUE TITLE
getCount for new StumbleUpon

### ISSUE THREAD

**Issue by Ruud68** [tabalinas/jssocials#45]
Hi,
I am working on new share: StumbleUpon, I cannot seem to get the share counter right :(

```
         stumbleupon: {
            label: "StumbleUpon",
            logo: "fa fa-stumbleupon",
            shareUrl: "http://www.stumbleupon.com/submit?url={url}&title={title}",
            countUrl:  "https://www.stumbleupon.com/services/1.01/badge.getinfo?url={url}",
            getCount: function(data) {
                return parseFloat((data.match(/\"views\":([.0-9E]+)/) || [])[1]);
            }
```

when I do https://www.stumbleupon.com/services/1.01/badge.getinfo?url=https://www.google.com
this is what is returned:
```
{"result":{"url":"https:\/\/www.google.com\/","in_index":true,"publicid":"1krtS0","views":14834,"title":"Google","thumbnail":"http:\/\/cdn.stumble-upon.com\/mthumb\/647\/5593647.jpg","thumbnail_b":"http:\/\/cdn.stumble-upon.com\/bthumb\/647\/5593647.jpg","submit_link":"http:\/\/www.stumbleupon.com\/badge\/?url=https:\/\/www.google.com\/","badge_link":"http:\/\/www.stumbleupon.com\/badge\/?url=https:\/\/www.google.com\/","info_link":"http:\/\/www.stumbleupon.com\/url\/https%253A\/\/www.google.com\/"},"timestamp":1455201235,"success":true}
```
What is de function / regex to get the views out of this response?
I'm really lacking Javascript knowledge :(
If I get this working and confirmed by a user I will do a PR for the changes :)

**Comment by tabalinas** [comment]
I believe that this is just JSON, so we can get it like `return data.result.views`.

**Comment by tabalinas** [comment]
The PR adding StumbleUpon would be great! Thanks for your efforts!

**Comment by Ruud68** [comment]
Hi, already tried the return data.result.views but that didn't work.
It turned out (learn something new every day :)) that the returned format was not jsonp.

Needed to call the return url with the prefix url: https://cors-anywhere.herokuapp.com/ (same as google plus).

now it works :)
One 'StumbleUpon' PR coming up :)
