### ISSUE TITLE
Can't get email adress on email share

### ISSUE THREAD

**Issue by eriklyngsoe** [tabalinas/jssocials#48]
I can 'r get the mail adress to be merged into the mailto querystring on the email share

Here is the script I've tried.

Can anybody help?

         <div id="shareIcons" style="text-align: right"></div>
                    <script>
                        $("#shareIcons").jsSocials({
                            url: "http://www.rampelys.dk",
                            text: "Rampelys Silkeborg",
                            showLabel: false,
                            showCount: false,
                            shares: [{ share: "email", label: "ely@rampelys.dk", text: "besked fra rampelys.dk", url:"" }, "facebook", "googleplus"] });

                        //$("#shareIcons").jsSocials("shareOption", "email", "text", "Besked fra www.rampelys.dk:");
                        //$("#shareIcons").jsSocials("shareOption", "email", "E-mail", "info@rampelys.dk");
                        //$("#shareIcons").jsSocials("shareOption", "email", "mailto", "info@rampelys.dk");
                        //$("#shareIcons").jsSocials("shareOption", "email", "url", "");

                    </script>

`

**Comment by tabalinas** [comment]
It's just that currently `to` for email sharing is not supported.
For now you can redefine the `email` share and use `to` option like the following:

```js
// update email share
jsSocials.shares.email.shareUrl = "mailto:{to}?subject={text}&body={url}";

// change the option
$("#shareIcons").jsSocials("shareOption", "email", "to", "info@rampelys.dk");

// or during initialization
$("#shareIcons").jsSocials({
    url: "http://www.rampelys.dk",
    text: "Rampelys Silkeborg",
    showLabel: false,
    showCount: false,
    shares: [{ share: "email", to: "ely@rampelys.dk"}, "facebook", "googleplus"] });
```

I'm going to add the parameter. Thanks for the feedback!

**Comment by eriklyngsoe** [comment]
What ever I do it will not merge the email adress into the link.

I will givbe it another  try in the upcomming weekend.

**Comment by tabalinas** [comment]
Have you tried code above?
If you'll download latest sources, you can use `to` option of `email` share. But anyway code above should work. It's tested. Just be sure that this script goes after linking `jssocials.js`.
