### ISSUE TITLE
Long page loading

### ISSUE THREAD

**Issue by Frostbourn** [tabalinas/jssocials#55]
Hi

Is it possible to call the `countUrl` globally (in eg: http://share-counters.rhcloud.com/?url={url}&callback=?) just once and then load `getCount` to shorten page load?

**Comment by tabalinas** [comment]
Hi, 

There is no direct way to do it. As a workaround you could redefine `_loadCount` method that should return a promise that will be resolved with the count and accepts a share config. The function could look like that (code is not tested):

```js
$("#jsSocials").jsSocials({
    ...

    _loadCount: (function() {
        var counts;

        return function(share) {
            var deferred = $.Deferred();

            if(counts) {
                deferred.resolve(counts.shares[share.share]);
            } else {
                $.getJSON(this._formatShareUrl("http://share-counters.rhcloud.com/?url={url}&callback=?", share)).done(function(result) {
                    counts = result;
                    deferred.resolve(counts.shares[share.share]);
                });
            }

            return deferred.promise();
        };
    }())
});
```
