### ISSUE TITLE
Update the Font-awesome on demo page

### ISSUE THREAD

**Issue by nasirkhan** [tabalinas/jssocials#56]
please update the font-awesome version for the demo site.

**Comment by tabalinas** [comment]
Could you tell me the purpose? Currently used version is 4.3, the latest one is 4.5. Something significant was changed since 2 minors?

**Comment by nasirkhan** [comment]
Well, the Google plus logo has been changed. So the "G+ +1" button looks
far different than the demo. If you update the version then you might want
to update the G+ button design as well.

Thanks

**Comment by tabalinas** [comment]
Thanks for the feedback!
