### ISSUE TITLE
Adding SVG base 64 support

### ISSUE THREAD

**Issue by CapitalH** [tabalinas/jssocials#57]
Hi

First of all thank you very very much for this wonderful and easy to use social sharing plugin. After searching for days I can say this is the best plugin ever.

I did some minor changes to the core files to add base64 svg support for social logos.

In jssocial.js file I changed line 16 to the following:

```javascript
var IMG_SRC_REGEX = /(\.(jpeg|png|gif|bmp|svg\+xml)$|^data:image\/(jpeg|png|gif|bmp|svg\+xml);base64)/i;
```

I hope this could help some people who just like me prefer SVG icons to font icons when you only need 1 or 2 of them.

**Comment by tabalinas** [comment]
Hi,
Thank you for the feedback, I appreciate it.
Could you do a pull request?

**Comment by tabalinas** [comment]
Implemented

**Comment by holographix** [comment]
Hi, I was trying this, but unfortunately It's not really working as expected, I have this scenario:

`$(".shareIcons").jsSocials({
		    showLabel: false,
		    showCount: false,
		    shares: [
		    	{ share: "facebook", 	logo: "/imgs/social/ico_social_fb.svg"}, 
		    	{ share: "twitter", 	logo: "/imgs/social/ico_social_tw.svg"}, 
		    	{ share: "linkedin", 	logo: "/imgs/social/ico_social_in.svg"}
		    ],

		});`

and basically what happens is that I get an <i></i> tag instead of an <img> one

**Comment by Ruud68** [comment]
have you tried ./imgs/social/ico_social_fb.svg or imgs/social/ico_social_fb.svg?
making the path relative instead of absolute?

**Comment by holographix** [comment]
yep.. :(

**Comment by holographix** [comment]
yep.. :(

**Comment by tabalinas** [comment]
@holographix, you are right. The issue is fixed.

**Comment by holographix** [comment]
jeez, that was fast!

**Comment by JoannaD87** [comment]
I'm using a local install of fontawesome SVG version, but the icons are rendering as question marks 
<img width="1275" alt="screen shot 2018-05-08 at 8 27 37 pm" src="https://user-images.githubusercontent.com/28561726/39773124-c46a512a-52ff-11e8-9179-0ea8503ec8b7.png">

I loaded: 


    
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">

    
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,500,700" rel="stylesheet">

    
    <link rel="stylesheet" href="css/fontawesome/fa-svg-with-js.css">

    
    <link rel="stylesheet" href="css/animate.css">

    
    <link rel="stylesheet" href="css/aos/aos.css">

    
    <link rel="stylesheet" href="css/jssocials/jssocials.css">

    
    <link rel="stylesheet" href="css/jssocials/jssocials-theme-plain.css">

    
    <link rel="stylesheet" href="css/styles.css">

    
    
    <script src="js/jquery/jquery-3.2.1.min.js"></script>

    
    <script type="text/javascript" src="js/jquery/jquery.touchSwipe.min.js"></script>

    
    <script src="js/bootstrap/bootstrap.bundle.js"></script>

    
    <script src="js/fontawesome/fontawesome-all.js"></script>

    
    <script type="text/javascript" src="js/aos/aos.js"></script>

    
    <script type="text/javascript" src="js/jssocials/jssocials.js"></script>

What am I missing?
