### ISSUE TITLE
How added Telegram Social...

### ISSUE THREAD

**Issue by Deltafox79** [tabalinas/jssocials#60]
#1) On jssocials.js

`      telegram: {
            label: "Telegram",
            logo: "fa fa-paper-plane",
            shareUrl: "tg://msg?text={url} {text}",
            countUrl: "",
            shareIn: "self"
        },`

on css : 

`.jssocials-share-telegram .jssocials-share-link{background:#2CA5E0}
.jssocials-share-telegram .jssocials-share-link:hover{background:#076D9F}`

Regards

**Comment by tabalinas** [comment]
Would you mind to do a Pull request?

**Comment by Deltafox79** [comment]
how do a pull request? Yes I hope that this change will be integrated in future versions ..

**Comment by tabalinas** [comment]
I believe docs is the best source: https://help.github.com/articles/using-pull-requests/

**Comment by Deltafox79** [comment]
Tk's for the link.. not all people use github on all feature.. like me.. sometimes just reply whit issue o feature request.. regards

**Comment by tabalinas** [comment]
Implemented
