### ISSUE TITLE
PopUp not working 

### ISSUE THREAD

**Issue by MuhammadEid** [tabalinas/jssocials#61]
http://game2mena.com/oldcss/full-program 

please look when load more post it's not working and i also use 

<script>
    $(function() {
        var url = "http://google.com";
        var text = "Some text to share";
        $("#shareInPopup").jsSocials({
            url: url,
            text: text,
            shareIn: "popup",
            showCount: "inside",
            shares: ["twitter", "facebook", "googleplus", "linkedin"] 
        });
    });
</script>

**Comment by tabalinas** [comment]
Could you provide jssocials configuration?
From what I see you don't use popup sharing.

**Comment by MuhammadEid** [comment]
<div id="shareInPopup"></div>

<script>
    $(function() {

        var url = "http://google.com";
        var text = "Some text to share";

        $("#shareInPopup").jsSocials({
            url: url,
            text: text,
            shareIn: "popup",
            showCount: false,
            shares: ["twitter", "facebook", "googleplus", "linkedin"]
        });

    });
</script>


this my code

**Comment by tabalinas** [comment]
Is it a problem for you to put it in the ticket?

**Comment by tabalinas** [comment]
Without configuration I'm not able to help.
On the site it looks like share in popup is not configured. 
See the configuration in the [docs](http://js-socials.com/docs/#configuration) - you should specify `shareIn: "popup"`.
