### ISSUE TITLE
Facebook closes

### ISSUE THREAD

**Issue by katzka** [tabalinas/jssocials#64]
Hi everything is working perfectly except facebook which opens and closes imediatly
Please if you have a way to solve this, please help me out

**Comment by tabalinas** [comment]
Have you tried it on the project site http://js-socials.com/? Do you have the same issue with facebook share?
If it's working fine, then we have to find differences in your configuration. If it's not working for the project site also, please, let me know the browser and the device your are using.

**Comment by katzka** [comment]
we figured it out by the end
I used the popup version end i used the:

$("#sharePopup").jsSocials({
    shareIn: "popup",
    shares: ["twitter", "facebook", "googleplus", "linkedin",
"pinterest", "stumbleupon"]});


then we added the


url: "http://www.mysite.com",  and this solved the problem


on the demo page that isnt obvious and i am a designer , a programmer
helped me out,

Thanks a lot it is a grate plugin

**Comment by tabalinas** [comment]
Glad that you figured it out!
