### ISSUE TITLE
Do not package the .sass-cache dir

### ISSUE THREAD

**Issue by ChALkeR** [tabalinas/jssocials#7]
*Disclaimer: I do not use the package, this was found during automated npm packages downloading.*

Your current package size is 1.1 KiB packed, **6.2 MiB** unpacked. 5.9 MiB of that are inside the `.sass-cache` dir. I suspect that this probably got packed to the release by mistake.

You could add that dir to the `.gitignore`.

**Comment by tabalinas** [comment]
`.sass-cache` dir is not included into the repo. I guess you added issue to wrong repo.

**Comment by ChALkeR** [comment]
No, I didn't. `.sass-cache` dir is included in your npm package.

**Comment by ChALkeR** [comment]
You probably forgot that you published your library to npm.

https://www.npmjs.com/package/jssocials:
> tabalin tabalin published 2 weeks ago

**Comment by ChALkeR** [comment]
Btw, you also published your `.idea` dir.

**Comment by tabalinas** [comment]
Sorry, my bad! I thought you was talking about git repo.

**Comment by ChALkeR** [comment]
=). I mentioned npm in the first sentance.
Probably I should have worded in a way so that would be more visible. I actually filed the same issue to several npm packages, copy-pasting most part of the text, and wrongly assumed that npm is the primary source for distribution for all of them.

I will fix the text for later issues, thanks.

**Comment by tabalinas** [comment]
Thank you for the report!
