### ISSUE TITLE
Use JsSocials theme icons with renderer functions

### ISSUE THREAD

**Issue by amidisgab** [tabalinas/jssocials#70]
Hi How do I use JsSocials Theme-icons with the renderer functions?

**Comment by tabalinas** [comment]
In fact, jssocials doesn't provide icons itself. By default font-awesome icons are used. Thus if you linked font-awesome you can use its icons as usual (adding classes like `fa fa-some-icon`).

**Comment by amidisgab** [comment]
Hi is there a way to use the JsSocials theme with the font-awesome icons in a renderer fuction?
For eg. the  shareRoundIcons theme...

**Comment by tabalinas** [comment]
The `renderer` is for really custom scenario, there you can put any jQuery elements combination (or HTML markup as a string). Thus, of course you can put elements using font-awesome icons. Again in the renderer you can use whatever you prefer.
