### ISSUE TITLE
Adding multiple js-social instances on one page

### ISSUE THREAD

**Issue by frazerf** [tabalinas/jssocials#71]
I'm trying to add js-social multiple times on a page but only one instance shows. Is there a way to display more than one instances?

**Comment by tabalinas** [comment]
Sure, multiple instances are supported.
Please, provide more info how exactly you configure several jssocials.

**Comment by frazerf** [comment]
Thanks for replying so quickly @tabalinas ! In a nut shell I have something like this - https://jsfiddle.net/2n23owj7/1/ I have three instances of js-social but for some reason only one instance is showing. Do you know why this is? Thanks again.

**Comment by Ruud68** [comment]
Hi, I ran into the same with my Joomla! plugin that utilizes the jssocials script.
What I did to solve it was make every occurrence of the buttons 'unique'
like this:
```
<div id="share764"><script type="text/javascript">jQuery("#share764"). jsSocials({shareIn: "popup",shares: [{ share: "twitter", label: "Tweet".....
```
The number 764 is random number so the second occurrence of the buttons on the same page could be something like:
```
<div id="share854"><script type="text/javascript">jQuery("#share854"). jsSocials({shareIn: "popup",shares: [{ share: "twitter", label: "Tweet".....
```
Hipe this helps :)

**Comment by tabalinas** [comment]
This is not about jssocials, this is about HTML. You cannot have several elements with the same id, thus when you select element with jQuery selector it gives you the first one. 
To solve the issue just use `.my-socials-sharing-class` instead on ids.

**Comment by frazerf** [comment]
So simple! Sorry, I really should of picked that up. Thanks again.
