### ISSUE TITLE
Doesn't work with gulp and main-bower-files plugin

### ISSUE THREAD

**Issue by matjazmav** [tabalinas/jssocials#72]
I can't get this to work with `gulp` and [`main-bower-files`](https://github.com/ck86/main-bower-files) plugin. I have checked `bower.json` all main files are there, but for some reason they doesn't get in the pipe.

This is snippet from my `gulpfile.js`:
```js
var gulp = require('gulp'),
    bower = require('main-bower-files'),
    concat = require('gulp-concat'),
    uglify = require('gulp-uglify'),
    plumber = require('gulp-plumber');

gulp.task('js', [], () => {
    var src = bower(['**/*.js']).concat([
        // Add custom files
    ]);
    return gulp.src(src)
        .pipe(plumber())
        .pipe(uglify())
        .pipe(concat('all.min.js'))
        .pipe(gulp.dest('dist/assets/js'));
});
```

Am I missing something?
Thanks

**Comment by matjazmav** [comment]
It was my mistake, missing dependency in my `bower.js`. You can close this, thanks.

**Comment by tabalinas** [comment]
Glad that you figured it out.
