### ISSUE TITLE
Share specific image for each instance

### ISSUE THREAD

**Issue by ClovisSC** [tabalinas/jssocials#74]
Hey! First, thank you for your wonderful work!
I have several instances of jssocials on a one-page website (one per article) and I try to share different contents (the image relative to the article) to Facebook, Twitter and Pinterest. But I can't figure out to do this...
Have I missed something in the doc?
Thanks!

**Comment by tabalinas** [comment]
Hi,

Thank you for the feedback.
Indeed, maybe it worth to put an example in the docs. You could do a simple each on elements and add url to share to data attribute:

```html
<div class="share" data-url="http://first.com"></div>
<div class="share" data-url="http://second.com"></div>
```

```js
$(".share").each(function() {
  $(this).jsSocials({
    ...
    url: $(this).data("url")
  });
});
```

**Comment by ClovisSC** [comment]
Oh yes, that should work!
Thanks :)
