### ISSUE TITLE
How To Custom Image Share

### ISSUE THREAD

**Issue by prakasa1904** [tabalinas/jssocials#76]
I want to share with custom image for facebook, twitter, g+, etc. in section of page. For example  : 

I have URL google.com with og image image.jpg, but I have div part with some image, and I want to share that. Can I do that with this plugin ?

**Comment by tabalinas** [comment]
Not sure I understand. What do you mean by "sharing a div"?
If it's possible to share "this" with native sharing buttons, most probably you can share it with js-socials.

**Comment by tabalinas** [comment]
Close due to inactivity
