### ISSUE TITLE
https://cors-anywhere.herokuapp.com?

### ISSUE THREAD

**Issue by biapar** [tabalinas/jssocials#77]
Hi,
Is't possible to remove https://cors-anywhere.herokuapp.com? 
What's this site?

**Comment by tabalinas** [comment]
Hi,
This resource allows to fetch sharing counts when cross-origin (domain) request is needed. 
Why do you need to remove it?

**Comment by biapar** [comment]
Hi,I see that waste some connection time and I don't know if the site track somethings without respect the privacy law.

Ing. Biagio PARUOLO




On Sat, Jul 23, 2016 at 10:21 AM +0200, "Artem Tabalin" <notifications@github.com> wrote:












Hi,

This resource allows to fetch sharing counts when cross-origin (domain) request is needed. 

Why do you need to remove it?

**Comment by tabalinas** [comment]
If you can propose any other way to get googleplus sharing count, I would change it with pleasure.
For now, I just don't know another way to do it.
If you want to avoid it, just redefine `countUrl` to an empty string for googleplus share. In this case count won't be retrieved.
