### ISSUE TITLE
Firefox Problem 

### ISSUE THREAD

**Issue by claudioromano13** [tabalinas/jssocials#79]
The styles of native buttons  don't work in firefox.

**Comment by tabalinas** [comment]
Could you provide more info on how to reproduce the issue?
I've checked the demo page in FF and it seems to look just fine.

**Comment by claudioromano13** [comment]
I applied the plug -in on my project and did not work well . Images of sending for analysis and an image displayed on firefox .
I like the project and I want to help improve.

![firefox-problem](https://cloud.githubusercontent.com/assets/7386266/17774959/86c02fec-652c-11e6-8dc6-7e72698608dd.jpg)
![my-app-internet-explorer](https://cloud.githubusercontent.com/assets/7386266/17774962/86c910b2-652c-11e6-963c-996db66c7938.png)
![my-app-firefox](https://cloud.githubusercontent.com/assets/7386266/17774960/86c27dd8-652c-11e6-9398-cdc0cd517081.png)
![my-app-chrome](https://cloud.githubusercontent.com/assets/7386266/17774961/86c280da-652c-11e6-88fa-230fe584a8a9.png)
![firefox-version](https://cloud.githubusercontent.com/assets/7386266/17775093/1e585f6e-652d-11e6-9b8f-c81f984ff44b.png)

**Comment by claudioromano13** [comment]
Hey guys , the problem is that Firefox blocked the plugin.
To solve: Firefox > Help > Restart with Add-ons Disabled

**Comment by claudioromano13** [comment]
Hey guys , the problem is that Firefox blocked the plugin. To solve: Firefox > Help > Restart with Add-ons Disabled

**Comment by tabalinas** [comment]
Do you think it could be that one of installed FF add-ons blocks social sharing controls?
Do you have any error message on the browser console?

**Comment by claudioromano13** [comment]
Certaintly, the add-ons block script, but don't block Google plus (!!!???!!!).
No console error.

**Comment by claudioromano13** [comment]
Tabalinas,
I restored firefox to resolve this issue.
Your project is working very well, the problem is in firefox.

**Comment by tabalinas** [comment]
Glad that you figured it out. Thank you for the feedback and the report!
