### ISSUE TITLE
Pulling in Data to facebook

### ISSUE THREAD

**Issue by mlauren** [tabalinas/jssocials#8]
When I use your script I can not get the data to display in the popout window for facebook. Here is my code

`$(".social-share-block").jsSocials({
    url: window.location.href,
    text: {TEXT HERE},
    showCount: false,
    showLabel: false,
    shares: [
      "email",
      "twitter",
      "facebook",
      "googleplus"
    ]
  });`

When  I use this, the facebook screen just displays the url and nothing else, the twitter popout includes url and text.

**Comment by tabalinas** [comment]
Facebook doesn't support providing text for sharing. The only this we can give to fb share is an actual resource url.

All the details about sharing resource should be added to `<head>` section of the markup of the sharing page with OpenGraph metas.

e.g. see how it looks for http://js-socials.com

```html
    <meta property="og:title" content="jsSocials - Simple Social Network Sharing Plugin"/>
    <meta property="og:site_name" content="jsSocials"/>
    <meta property="og:url" content="http://js-socials.com"/>
    <meta property="og:description" content="Simple Social Network Sharing Plugin"/>
    <meta property="og:image" content=""/>
```

Read more about it here http://ogp.me/

**Comment by Ruud68** [comment]
Please Note: if you have gzipped your webpage, Facebook cannot read info from it!

**Comment by fraferrando** [comment]
Excuse me, i've put the tag in the head section of my _Layout.cshtml (MVC Project)  but still I can't view the title... 
can you help me?
