### ISSUE TITLE
Facebook share error since today

### ISSUE THREAD

**Issue by LDSign** [tabalinas/jssocials#80]
Hi

The facebook share or facebook itself throws an error since this morning:

"OAuthException: (#12) fql is deprecated for versions v2.1 and higher"

Could you have a look at it?

Thanks,
Frank

**Comment by mustafaonurcelik** [comment]
OK. here is my fast solution..

replace those lines in jssocials.js.. (line : 448 to 458)

facebook: {
            label: "Like",
            logo: "fa fa-facebook",
            shareUrl: "https://facebook.com/sharer/sharer.php?u={url}",
            countUrl: function() {
                return "http://graph.facebook.com/?id=" + this.url;
            },
            getCount: function(data) {
                return data.share.share_count;
            }
        },

**Comment by LDSign** [comment]
Hi

Thanks for your answer. But this is getting me

Uncaught TypeError: Cannot read property 'share_count' of undefined

:(

Frank

**Comment by tabalinas** [comment]
@mustafaonurcelik, thank you for the solution.

@LDSign, seems to work fine for me. Are you sure you have shares for this url? 
I think, this check should be enough:

```js
getCount: function(data) {
   return data.share && data.share.share_count || 0;
}
```

**Comment by mustafaonurcelik** [comment]
unfortunately this solution is also dead as of today :(

**Comment by tabalinas** [comment]
Are you sure? It's still working for the demo page http://js-socials.com/demos/

Why do you think it's dead?

**Comment by mustafaonurcelik** [comment]
I was getting error #403 but now it's OK, i don't know why.
