### ISSUE TITLE
how to show image in email sharing and Line app sharing

### ISSUE THREAD

**Issue by supercreator** [tabalinas/jssocials#86]
This plug in is nice! How can I add image content, url image, into main content, then it will show image in mail or line chat room. 

Thank you

**Comment by tabalinas** [comment]
Currently built-in `line` share supports only text sharing. 
So to share an image you need to change the `shareUrl` in the config of the share according to the format 2 described in the [docs](https://media.line.me/howto/en/).

**Comment by supercreator** [comment]
Thank you Artem, if there are the new version, I will update it surely.
