### ISSUE TITLE
instagram support

### ISSUE THREAD

**Issue by wezy01** [tabalinas/jssocials#87]
Hello,
any chance jssocial will be supporting sharing to Instagram in the future?

With kind regards,
Erwin

**Comment by tabalinas** [comment]
Why not, it should be easy J
Also feel free to do a PR. In fact all what we need is to find out `shareUrl` and `countUrl` to do an actual share and to get shares count accordingly (the second is optional).

**Comment by nidzo80** [comment]
It is old quote but still actual:

> "At this time, uploading via the API is not possible. We made a conscious choice not to add this for the following reasons:

> Instagram is about your life on the go – we hope to encourage photos from within the app. However, in the future we may give whitelist access to individual apps on a case by case basis.

> We want to fight spam & low quality photos. Once we allow uploading from other sources, it's harder to control what comes into the Instagram ecosystem. All this being said, we're working on ways to ensure users have a consistent and high-quality experience on our platform."

**Comment by tabalinas** [comment]
@nidzo80, you right! Completely forgot.
Please, checkout the following issue https://github.com/tabalinas/jssocials/issues/58
