### ISSUE TITLE
Save to Pocket - is it possible?

### ISSUE THREAD

**Issue by nidzo80** [tabalinas/jssocials#88]
**Pocket**  is read it later service and they allow to put their [buttons](https://getpocket.com/publisher/button) on web sites.
This is code for inserting button:
```
<a data-pocket-label="pocket" data-pocket-count="horizontal" class="pocket-btn" data-lang="en"></a>
<script type="text/javascript">!function(d,i){if(!d.getElementById(i)){var j=d.createElement("script");j.id=i;j.src="https://widgets.getpocket.com/v1/j/btn.js?v=1";var w=d.getElementById(i);d.body.appendChild(j);}}(document,"pocket-btn-js");</script>

```

> In order to support multiple buttons on a page, you place the button code anywhere you would like a Pocket button to appear. Then, for each button, you will need to simply add a data-save-url attribute to the <a> in your button code. The value of this attribute should be the url of the corresponding link that you are placing the button next to.

```
<a href="https://getpocket.com/save" class="pocket-btn" data-lang="en"
  data-save-url="http://yourDomain.com/the/page/to/save.html"
  data-pocket-count="vertical" 
  data-pocket-align="left"
  >Pocket</a>
<script type="text/javascript">...
```
Is it possible to include Save to Pocket in **jssocials** and also in Joomla plugin by @Ruud68 ?
[
Pocket Button Documentation](https://getpocket.com/publisher/button_docs)

**Comment by Ruud68** [comment]
Hi @nidzo80 when implemented in the script, I will implement it in the Joomla plugin :)

Could you try this sharing url?
https://getpocket.com/save?url=%post_full_url%&title=%post_title%

**Comment by nidzo80** [comment]
Adding code bellow in **jssocials.min.js** works: 
`pocket:{label:"Pocket",logo:"fa fa-get-pocket",shareUrl:"https://getpocket.com/save?url={url}&title={title}",countUrl:"",shareIn:"blank"}`

Tested on PC and Android device using your plugin :)

**Comment by Ruud68** [comment]
Cool, will do a PR here for pocket tomorrow, will 'ping' you on my forum with new Joomla plugin for testing

**Comment by nidzo80** [comment]
Great! 
You can see it in action on http://zanimljivedestinacije.info/lepote-srbije/52-posjetite-najlepsa-etno-sela-srbije.html
I didn't include Pocket in CSS files because I use custom icons.

**Comment by Ruud68** [comment]
gogogo: https://onlinecommunityhub.nl/forum/jssocials/40-new-pocket-button-testing-needed

**Comment by Ruud68** [comment]
https://github.com/tabalinas/jssocials/pull/89
