### ISSUE TITLE
Facebook / G+ counts still not working after upgrade

### ISSUE THREAD

**Issue by K-Thompson** [tabalinas/jssocials#91]
I updated my code to the Aug. 31 release by simply replacing the jssocials.min.js. I still don't see Facebook or G+ counts. Did I miss a step?  (I replaced v1.2.1 from May 18th with v.1.3.1) The site is HTML5/CSS3 on HTTPS.

Example page:

https://financial-calculators.com/amortization-schedule

**Comment by tabalinas** [comment]
For FB the fix for `https` is not released yet. 
You can fix for now adding config before initializing jsSocials:
```js
jsSocials.shares.facebook.countUrl = "https://graph.facebook.com/?id={url}";
```

As for GooglePlus, looks like https://cors-anywhere.herokuapp.com/ is blocked.
So now, it's not clear to me how to get google shares count. Please, share any input, if you know any stable alternative for CORS requests or any other way to get googleplus share count.

**Comment by PapayaMedia** [comment]
I'm seeing FB count using this code:

> jsSocials.shares.facebook = {
>         'label': "Like",
>         'logo': "fa fa-facebook",
>         'shareUrl': "https://facebook.com/sharer/sharer.php?u={url}",
>         'countUrl': "http://graph.facebook.com/?id={url}",
>         'getCount': function(data) {
>           return data.share.share_count; // <-- This modification did the trick.
>         }
>       };

PD: I don't know how to make this piece of code to be shown correctly.

**Comment by tabalinas** [comment]
@PapayaMedia, the issue here with FB is `http` instead of `https`, in the released version it's still `http`, but in the sources it's fixed https://github.com/tabalinas/jssocials/blob/master/src/jssocials.shares.js

**Comment by K-Thompson** [comment]
Thanks for your reply @tabalinas and guidance. Sorry, I have no knowledge of CORS.

**Comment by tabalinas** [comment]
A separate issue for Google plus shares count https://github.com/tabalinas/jssocials/issues/92
