### ISSUE TITLE
facebook post image

### ISSUE THREAD

**Issue by mlutfi10** [tabalinas/jssocials#97]
how can i set facebook + gplus + linkedin post image?

**Comment by Ruud68** [comment]
you can but not in the script.
what happens is the following:
1. you post the url to facebook / google+ / linkedin
2. they visit your page and 'scrape' information from it including the image

here is the facebook debuging tool that shows what they see on your page, what they use and what is missing: https://developers.facebook.com/tools/debug/sharing/ (just put in your url)

Facebook uses the og: metatags tags (like og: image) from your website as a first preference. If that information is not found then they will just use one of the first images they encounter. The share text comes from the meta description, if not set they figure it out themselves.

metatags are not a feature of this script but is a (in case of a cms) template feature (or another plugin that does 'the magic')

**Comment by tabalinas** [comment]
@Ruud68, thank you for the answer.
This issue could be also useful https://github.com/tabalinas/jssocials/issues/8.

**Comment by mlutfi10** [comment]
@Ruud68 @tabalinas yes thanks guys for ur answer
